package com.fulan.application.achievement.mapper;

import com.fulan.application.achievement.domain.FwdAgentInfo;
import com.fulan.application.achievement.domain.FwdAgentInfoExample;
import java.util.List;

import org.apache.ibatis.annotations.Mapper;
import org.apache.ibatis.annotations.Param;
@Mapper
public interface FwdAgentInfoMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table fwd_agent_info
     *
     * @mbggenerated Wed May 23 17:26:10 CST 2018
     */
    int countByExample(FwdAgentInfoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table fwd_agent_info
     *
     * @mbggenerated Wed May 23 17:26:10 CST 2018
     */
    int deleteByExample(FwdAgentInfoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table fwd_agent_info
     *
     * @mbggenerated Wed May 23 17:26:10 CST 2018
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table fwd_agent_info
     *
     * @mbggenerated Wed May 23 17:26:10 CST 2018
     */
    int insert(FwdAgentInfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table fwd_agent_info
     *
     * @mbggenerated Wed May 23 17:26:10 CST 2018
     */
    int insertSelective(FwdAgentInfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table fwd_agent_info
     *
     * @mbggenerated Wed May 23 17:26:10 CST 2018
     */
    List<FwdAgentInfo> selectByExample(FwdAgentInfoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table fwd_agent_info
     *
     * @mbggenerated Wed May 23 17:26:10 CST 2018
     */
    FwdAgentInfo selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table fwd_agent_info
     *
     * @mbggenerated Wed May 23 17:26:10 CST 2018
     */
    int updateByExampleSelective(@Param("record") FwdAgentInfo record, @Param("example") FwdAgentInfoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table fwd_agent_info
     *
     * @mbggenerated Wed May 23 17:26:10 CST 2018
     */
    int updateByExample(@Param("record") FwdAgentInfo record, @Param("example") FwdAgentInfoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table fwd_agent_info
     *
     * @mbggenerated Wed May 23 17:26:10 CST 2018
     */
    int updateByPrimaryKeySelective(FwdAgentInfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table fwd_agent_info
     *
     * @mbggenerated Wed May 23 17:26:10 CST 2018
     */
    int updateByPrimaryKey(FwdAgentInfo record);
}