package com.zwo.modules.cms.domain;

import java.io.Serializable;

public class CmsDocumentWithBLOBs extends CmsDocument implements Serializable {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cms_document.EN_CONTENT
     *
     * @mbggenerated Mon Jun 05 16:10:10 CST 2017
     */
    private String enContent;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cms_document.M_CONTENT
     *
     * @mbggenerated Mon Jun 05 16:10:10 CST 2017
     */
    private String mContent;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cms_document.CONTENT
     *
     * @mbggenerated Mon Jun 05 16:10:10 CST 2017
     */
    private String content;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table cms_document
     *
     * @mbggenerated Mon Jun 05 16:10:10 CST 2017
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cms_document.EN_CONTENT
     *
     * @return the value of cms_document.EN_CONTENT
     *
     * @mbggenerated Mon Jun 05 16:10:10 CST 2017
     */
    public String getEnContent() {
        return enContent;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cms_document.EN_CONTENT
     *
     * @param enContent the value for cms_document.EN_CONTENT
     *
     * @mbggenerated Mon Jun 05 16:10:10 CST 2017
     */
    public void setEnContent(String enContent) {
        this.enContent = enContent == null ? null : enContent.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cms_document.M_CONTENT
     *
     * @return the value of cms_document.M_CONTENT
     *
     * @mbggenerated Mon Jun 05 16:10:10 CST 2017
     */
    public String getmContent() {
        return mContent;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cms_document.M_CONTENT
     *
     * @param mContent the value for cms_document.M_CONTENT
     *
     * @mbggenerated Mon Jun 05 16:10:10 CST 2017
     */
    public void setmContent(String mContent) {
        this.mContent = mContent == null ? null : mContent.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cms_document.CONTENT
     *
     * @return the value of cms_document.CONTENT
     *
     * @mbggenerated Mon Jun 05 16:10:10 CST 2017
     */
    public String getContent() {
        return content;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cms_document.CONTENT
     *
     * @param content the value for cms_document.CONTENT
     *
     * @mbggenerated Mon Jun 05 16:10:10 CST 2017
     */
    public void setContent(String content) {
        this.content = content == null ? null : content.trim();
    }
}