package com.zwo.modules.member.domain;

import java.util.ArrayList;
import java.util.List;

public class GroupPurcseMemberCriteria {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table group_purcse_member
     *
     * @mbggenerated Wed Sep 13 09:19:02 CST 2017
     */
    protected String orderByClause;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table group_purcse_member
     *
     * @mbggenerated Wed Sep 13 09:19:02 CST 2017
     */
    protected boolean distinct;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table group_purcse_member
     *
     * @mbggenerated Wed Sep 13 09:19:02 CST 2017
     */
    protected List<Criteria> oredCriteria;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table group_purcse_member
     *
     * @mbggenerated Wed Sep 13 09:19:02 CST 2017
     */
    public GroupPurcseMemberCriteria() {
        oredCriteria = new ArrayList<Criteria>();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table group_purcse_member
     *
     * @mbggenerated Wed Sep 13 09:19:02 CST 2017
     */
    public void setOrderByClause(String orderByClause) {
        this.orderByClause = orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table group_purcse_member
     *
     * @mbggenerated Wed Sep 13 09:19:02 CST 2017
     */
    public String getOrderByClause() {
        return orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table group_purcse_member
     *
     * @mbggenerated Wed Sep 13 09:19:02 CST 2017
     */
    public void setDistinct(boolean distinct) {
        this.distinct = distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table group_purcse_member
     *
     * @mbggenerated Wed Sep 13 09:19:02 CST 2017
     */
    public boolean isDistinct() {
        return distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table group_purcse_member
     *
     * @mbggenerated Wed Sep 13 09:19:02 CST 2017
     */
    public List<Criteria> getOredCriteria() {
        return oredCriteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table group_purcse_member
     *
     * @mbggenerated Wed Sep 13 09:19:02 CST 2017
     */
    public void or(Criteria criteria) {
        oredCriteria.add(criteria);
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table group_purcse_member
     *
     * @mbggenerated Wed Sep 13 09:19:02 CST 2017
     */
    public Criteria or() {
        Criteria criteria = createCriteriaInternal();
        oredCriteria.add(criteria);
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table group_purcse_member
     *
     * @mbggenerated Wed Sep 13 09:19:02 CST 2017
     */
    public Criteria createCriteria() {
        Criteria criteria = createCriteriaInternal();
        if (oredCriteria.size() == 0) {
            oredCriteria.add(criteria);
        }
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table group_purcse_member
     *
     * @mbggenerated Wed Sep 13 09:19:02 CST 2017
     */
    protected Criteria createCriteriaInternal() {
        Criteria criteria = new Criteria();
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table group_purcse_member
     *
     * @mbggenerated Wed Sep 13 09:19:02 CST 2017
     */
    public void clear() {
        oredCriteria.clear();
        orderByClause = null;
        distinct = false;
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table group_purcse_member
     *
     * @mbggenerated Wed Sep 13 09:19:02 CST 2017
     */
    protected abstract static class GeneratedCriteria {
        protected List<Criterion> criteria;

        protected GeneratedCriteria() {
            super();
            criteria = new ArrayList<Criterion>();
        }

        public boolean isValid() {
            return criteria.size() > 0;
        }

        public List<Criterion> getAllCriteria() {
            return criteria;
        }

        public List<Criterion> getCriteria() {
            return criteria;
        }

        protected void addCriterion(String condition) {
            if (condition == null) {
                throw new RuntimeException("Value for condition cannot be null");
            }
            criteria.add(new Criterion(condition));
        }

        protected void addCriterion(String condition, Object value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value));
        }

        protected void addCriterion(String condition, Object value1, Object value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value1, value2));
        }

        public Criteria andIdIsNull() {
            addCriterion("ID is null");
            return (Criteria) this;
        }

        public Criteria andIdIsNotNull() {
            addCriterion("ID is not null");
            return (Criteria) this;
        }

        public Criteria andIdEqualTo(String value) {
            addCriterion("ID =", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotEqualTo(String value) {
            addCriterion("ID <>", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdGreaterThan(String value) {
            addCriterion("ID >", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdGreaterThanOrEqualTo(String value) {
            addCriterion("ID >=", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdLessThan(String value) {
            addCriterion("ID <", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdLessThanOrEqualTo(String value) {
            addCriterion("ID <=", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdLike(String value) {
            addCriterion("ID like", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotLike(String value) {
            addCriterion("ID not like", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdIn(List<String> values) {
            addCriterion("ID in", values, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotIn(List<String> values) {
            addCriterion("ID not in", values, "id");
            return (Criteria) this;
        }

        public Criteria andIdBetween(String value1, String value2) {
            addCriterion("ID between", value1, value2, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotBetween(String value1, String value2) {
            addCriterion("ID not between", value1, value2, "id");
            return (Criteria) this;
        }

        public Criteria andGroupPurcseIdIsNull() {
            addCriterion("GROUP_PURCSE_ID is null");
            return (Criteria) this;
        }

        public Criteria andGroupPurcseIdIsNotNull() {
            addCriterion("GROUP_PURCSE_ID is not null");
            return (Criteria) this;
        }

        public Criteria andGroupPurcseIdEqualTo(String value) {
            addCriterion("GROUP_PURCSE_ID =", value, "groupPurcseId");
            return (Criteria) this;
        }

        public Criteria andGroupPurcseIdNotEqualTo(String value) {
            addCriterion("GROUP_PURCSE_ID <>", value, "groupPurcseId");
            return (Criteria) this;
        }

        public Criteria andGroupPurcseIdGreaterThan(String value) {
            addCriterion("GROUP_PURCSE_ID >", value, "groupPurcseId");
            return (Criteria) this;
        }

        public Criteria andGroupPurcseIdGreaterThanOrEqualTo(String value) {
            addCriterion("GROUP_PURCSE_ID >=", value, "groupPurcseId");
            return (Criteria) this;
        }

        public Criteria andGroupPurcseIdLessThan(String value) {
            addCriterion("GROUP_PURCSE_ID <", value, "groupPurcseId");
            return (Criteria) this;
        }

        public Criteria andGroupPurcseIdLessThanOrEqualTo(String value) {
            addCriterion("GROUP_PURCSE_ID <=", value, "groupPurcseId");
            return (Criteria) this;
        }

        public Criteria andGroupPurcseIdLike(String value) {
            addCriterion("GROUP_PURCSE_ID like", value, "groupPurcseId");
            return (Criteria) this;
        }

        public Criteria andGroupPurcseIdNotLike(String value) {
            addCriterion("GROUP_PURCSE_ID not like", value, "groupPurcseId");
            return (Criteria) this;
        }

        public Criteria andGroupPurcseIdIn(List<String> values) {
            addCriterion("GROUP_PURCSE_ID in", values, "groupPurcseId");
            return (Criteria) this;
        }

        public Criteria andGroupPurcseIdNotIn(List<String> values) {
            addCriterion("GROUP_PURCSE_ID not in", values, "groupPurcseId");
            return (Criteria) this;
        }

        public Criteria andGroupPurcseIdBetween(String value1, String value2) {
            addCriterion("GROUP_PURCSE_ID between", value1, value2, "groupPurcseId");
            return (Criteria) this;
        }

        public Criteria andGroupPurcseIdNotBetween(String value1, String value2) {
            addCriterion("GROUP_PURCSE_ID not between", value1, value2, "groupPurcseId");
            return (Criteria) this;
        }

        public Criteria andMemberIdIsNull() {
            addCriterion("MEMBER_ID is null");
            return (Criteria) this;
        }

        public Criteria andMemberIdIsNotNull() {
            addCriterion("MEMBER_ID is not null");
            return (Criteria) this;
        }

        public Criteria andMemberIdEqualTo(String value) {
            addCriterion("MEMBER_ID =", value, "memberId");
            return (Criteria) this;
        }

        public Criteria andMemberIdNotEqualTo(String value) {
            addCriterion("MEMBER_ID <>", value, "memberId");
            return (Criteria) this;
        }

        public Criteria andMemberIdGreaterThan(String value) {
            addCriterion("MEMBER_ID >", value, "memberId");
            return (Criteria) this;
        }

        public Criteria andMemberIdGreaterThanOrEqualTo(String value) {
            addCriterion("MEMBER_ID >=", value, "memberId");
            return (Criteria) this;
        }

        public Criteria andMemberIdLessThan(String value) {
            addCriterion("MEMBER_ID <", value, "memberId");
            return (Criteria) this;
        }

        public Criteria andMemberIdLessThanOrEqualTo(String value) {
            addCriterion("MEMBER_ID <=", value, "memberId");
            return (Criteria) this;
        }

        public Criteria andMemberIdLike(String value) {
            addCriterion("MEMBER_ID like", value, "memberId");
            return (Criteria) this;
        }

        public Criteria andMemberIdNotLike(String value) {
            addCriterion("MEMBER_ID not like", value, "memberId");
            return (Criteria) this;
        }

        public Criteria andMemberIdIn(List<String> values) {
            addCriterion("MEMBER_ID in", values, "memberId");
            return (Criteria) this;
        }

        public Criteria andMemberIdNotIn(List<String> values) {
            addCriterion("MEMBER_ID not in", values, "memberId");
            return (Criteria) this;
        }

        public Criteria andMemberIdBetween(String value1, String value2) {
            addCriterion("MEMBER_ID between", value1, value2, "memberId");
            return (Criteria) this;
        }

        public Criteria andMemberIdNotBetween(String value1, String value2) {
            addCriterion("MEMBER_ID not between", value1, value2, "memberId");
            return (Criteria) this;
        }

        public Criteria andMemberNameIsNull() {
            addCriterion("MEMBER_NAME is null");
            return (Criteria) this;
        }

        public Criteria andMemberNameIsNotNull() {
            addCriterion("MEMBER_NAME is not null");
            return (Criteria) this;
        }

        public Criteria andMemberNameEqualTo(String value) {
            addCriterion("MEMBER_NAME =", value, "memberName");
            return (Criteria) this;
        }

        public Criteria andMemberNameNotEqualTo(String value) {
            addCriterion("MEMBER_NAME <>", value, "memberName");
            return (Criteria) this;
        }

        public Criteria andMemberNameGreaterThan(String value) {
            addCriterion("MEMBER_NAME >", value, "memberName");
            return (Criteria) this;
        }

        public Criteria andMemberNameGreaterThanOrEqualTo(String value) {
            addCriterion("MEMBER_NAME >=", value, "memberName");
            return (Criteria) this;
        }

        public Criteria andMemberNameLessThan(String value) {
            addCriterion("MEMBER_NAME <", value, "memberName");
            return (Criteria) this;
        }

        public Criteria andMemberNameLessThanOrEqualTo(String value) {
            addCriterion("MEMBER_NAME <=", value, "memberName");
            return (Criteria) this;
        }

        public Criteria andMemberNameLike(String value) {
            addCriterion("MEMBER_NAME like", value, "memberName");
            return (Criteria) this;
        }

        public Criteria andMemberNameNotLike(String value) {
            addCriterion("MEMBER_NAME not like", value, "memberName");
            return (Criteria) this;
        }

        public Criteria andMemberNameIn(List<String> values) {
            addCriterion("MEMBER_NAME in", values, "memberName");
            return (Criteria) this;
        }

        public Criteria andMemberNameNotIn(List<String> values) {
            addCriterion("MEMBER_NAME not in", values, "memberName");
            return (Criteria) this;
        }

        public Criteria andMemberNameBetween(String value1, String value2) {
            addCriterion("MEMBER_NAME between", value1, value2, "memberName");
            return (Criteria) this;
        }

        public Criteria andMemberNameNotBetween(String value1, String value2) {
            addCriterion("MEMBER_NAME not between", value1, value2, "memberName");
            return (Criteria) this;
        }

        public Criteria andMemberIconIsNull() {
            addCriterion("MEMBER_ICON is null");
            return (Criteria) this;
        }

        public Criteria andMemberIconIsNotNull() {
            addCriterion("MEMBER_ICON is not null");
            return (Criteria) this;
        }

        public Criteria andMemberIconEqualTo(String value) {
            addCriterion("MEMBER_ICON =", value, "memberIcon");
            return (Criteria) this;
        }

        public Criteria andMemberIconNotEqualTo(String value) {
            addCriterion("MEMBER_ICON <>", value, "memberIcon");
            return (Criteria) this;
        }

        public Criteria andMemberIconGreaterThan(String value) {
            addCriterion("MEMBER_ICON >", value, "memberIcon");
            return (Criteria) this;
        }

        public Criteria andMemberIconGreaterThanOrEqualTo(String value) {
            addCriterion("MEMBER_ICON >=", value, "memberIcon");
            return (Criteria) this;
        }

        public Criteria andMemberIconLessThan(String value) {
            addCriterion("MEMBER_ICON <", value, "memberIcon");
            return (Criteria) this;
        }

        public Criteria andMemberIconLessThanOrEqualTo(String value) {
            addCriterion("MEMBER_ICON <=", value, "memberIcon");
            return (Criteria) this;
        }

        public Criteria andMemberIconLike(String value) {
            addCriterion("MEMBER_ICON like", value, "memberIcon");
            return (Criteria) this;
        }

        public Criteria andMemberIconNotLike(String value) {
            addCriterion("MEMBER_ICON not like", value, "memberIcon");
            return (Criteria) this;
        }

        public Criteria andMemberIconIn(List<String> values) {
            addCriterion("MEMBER_ICON in", values, "memberIcon");
            return (Criteria) this;
        }

        public Criteria andMemberIconNotIn(List<String> values) {
            addCriterion("MEMBER_ICON not in", values, "memberIcon");
            return (Criteria) this;
        }

        public Criteria andMemberIconBetween(String value1, String value2) {
            addCriterion("MEMBER_ICON between", value1, value2, "memberIcon");
            return (Criteria) this;
        }

        public Criteria andMemberIconNotBetween(String value1, String value2) {
            addCriterion("MEMBER_ICON not between", value1, value2, "memberIcon");
            return (Criteria) this;
        }

        public Criteria andMemberOpenIdIsNull() {
            addCriterion("MEMBER_OPEN_ID is null");
            return (Criteria) this;
        }

        public Criteria andMemberOpenIdIsNotNull() {
            addCriterion("MEMBER_OPEN_ID is not null");
            return (Criteria) this;
        }

        public Criteria andMemberOpenIdEqualTo(String value) {
            addCriterion("MEMBER_OPEN_ID =", value, "memberOpenId");
            return (Criteria) this;
        }

        public Criteria andMemberOpenIdNotEqualTo(String value) {
            addCriterion("MEMBER_OPEN_ID <>", value, "memberOpenId");
            return (Criteria) this;
        }

        public Criteria andMemberOpenIdGreaterThan(String value) {
            addCriterion("MEMBER_OPEN_ID >", value, "memberOpenId");
            return (Criteria) this;
        }

        public Criteria andMemberOpenIdGreaterThanOrEqualTo(String value) {
            addCriterion("MEMBER_OPEN_ID >=", value, "memberOpenId");
            return (Criteria) this;
        }

        public Criteria andMemberOpenIdLessThan(String value) {
            addCriterion("MEMBER_OPEN_ID <", value, "memberOpenId");
            return (Criteria) this;
        }

        public Criteria andMemberOpenIdLessThanOrEqualTo(String value) {
            addCriterion("MEMBER_OPEN_ID <=", value, "memberOpenId");
            return (Criteria) this;
        }

        public Criteria andMemberOpenIdLike(String value) {
            addCriterion("MEMBER_OPEN_ID like", value, "memberOpenId");
            return (Criteria) this;
        }

        public Criteria andMemberOpenIdNotLike(String value) {
            addCriterion("MEMBER_OPEN_ID not like", value, "memberOpenId");
            return (Criteria) this;
        }

        public Criteria andMemberOpenIdIn(List<String> values) {
            addCriterion("MEMBER_OPEN_ID in", values, "memberOpenId");
            return (Criteria) this;
        }

        public Criteria andMemberOpenIdNotIn(List<String> values) {
            addCriterion("MEMBER_OPEN_ID not in", values, "memberOpenId");
            return (Criteria) this;
        }

        public Criteria andMemberOpenIdBetween(String value1, String value2) {
            addCriterion("MEMBER_OPEN_ID between", value1, value2, "memberOpenId");
            return (Criteria) this;
        }

        public Criteria andMemberOpenIdNotBetween(String value1, String value2) {
            addCriterion("MEMBER_OPEN_ID not between", value1, value2, "memberOpenId");
            return (Criteria) this;
        }

        public Criteria andIdLikeInsensitive(String value) {
            addCriterion("upper(ID) like", value.toUpperCase(), "id");
            return (Criteria) this;
        }

        public Criteria andGroupPurcseIdLikeInsensitive(String value) {
            addCriterion("upper(GROUP_PURCSE_ID) like", value.toUpperCase(), "groupPurcseId");
            return (Criteria) this;
        }

        public Criteria andMemberIdLikeInsensitive(String value) {
            addCriterion("upper(MEMBER_ID) like", value.toUpperCase(), "memberId");
            return (Criteria) this;
        }

        public Criteria andMemberNameLikeInsensitive(String value) {
            addCriterion("upper(MEMBER_NAME) like", value.toUpperCase(), "memberName");
            return (Criteria) this;
        }

        public Criteria andMemberIconLikeInsensitive(String value) {
            addCriterion("upper(MEMBER_ICON) like", value.toUpperCase(), "memberIcon");
            return (Criteria) this;
        }

        public Criteria andMemberOpenIdLikeInsensitive(String value) {
            addCriterion("upper(MEMBER_OPEN_ID) like", value.toUpperCase(), "memberOpenId");
            return (Criteria) this;
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table group_purcse_member
     *
     * @mbggenerated do_not_delete_during_merge Wed Sep 13 09:19:02 CST 2017
     */
    public static class Criteria extends GeneratedCriteria {

        protected Criteria() {
            super();
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table group_purcse_member
     *
     * @mbggenerated Wed Sep 13 09:19:02 CST 2017
     */
    public static class Criterion {
        private String condition;

        private Object value;

        private Object secondValue;

        private boolean noValue;

        private boolean singleValue;

        private boolean betweenValue;

        private boolean listValue;

        private String typeHandler;

        public String getCondition() {
            return condition;
        }

        public Object getValue() {
            return value;
        }

        public Object getSecondValue() {
            return secondValue;
        }

        public boolean isNoValue() {
            return noValue;
        }

        public boolean isSingleValue() {
            return singleValue;
        }

        public boolean isBetweenValue() {
            return betweenValue;
        }

        public boolean isListValue() {
            return listValue;
        }

        public String getTypeHandler() {
            return typeHandler;
        }

        protected Criterion(String condition) {
            super();
            this.condition = condition;
            this.typeHandler = null;
            this.noValue = true;
        }

        protected Criterion(String condition, Object value, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.typeHandler = typeHandler;
            if (value instanceof List<?>) {
                this.listValue = true;
            } else {
                this.singleValue = true;
            }
        }

        protected Criterion(String condition, Object value) {
            this(condition, value, null);
        }

        protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.secondValue = secondValue;
            this.typeHandler = typeHandler;
            this.betweenValue = true;
        }

        protected Criterion(String condition, Object value, Object secondValue) {
            this(condition, value, secondValue, null);
        }
    }
}