package com.zwo.modules.system.mapper;

import com.zwo.modules.system.domain.RoleResource;
import com.zwo.modules.system.domain.RoleResourceCriteria;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface RoleResourceMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bhm_role_res
     *
     * @mbg.generated Thu Sep 20 15:46:20 CST 2018
     */
    long countByExample(RoleResourceCriteria example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bhm_role_res
     *
     * @mbg.generated Thu Sep 20 15:46:20 CST 2018
     */
    int deleteByExample(RoleResourceCriteria example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bhm_role_res
     *
     * @mbg.generated Thu Sep 20 15:46:20 CST 2018
     */
    int insert(RoleResource record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bhm_role_res
     *
     * @mbg.generated Thu Sep 20 15:46:20 CST 2018
     */
    int insertSelective(RoleResource record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bhm_role_res
     *
     * @mbg.generated Thu Sep 20 15:46:20 CST 2018
     */
    List<RoleResource> selectByExample(RoleResourceCriteria example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bhm_role_res
     *
     * @mbg.generated Thu Sep 20 15:46:20 CST 2018
     */
    int updateByExampleSelective(@Param("record") RoleResource record, @Param("example") RoleResourceCriteria example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bhm_role_res
     *
     * @mbg.generated Thu Sep 20 15:46:20 CST 2018
     */
    int updateByExample(@Param("record") RoleResource record, @Param("example") RoleResourceCriteria example);
}