package com.zwo.modules.mall.dao;

import com.zwo.modules.mall.domain.PrCategory;
import com.zwo.modules.mall.domain.PrCategoryCriteria;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface PrCategoryMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pr_category
     *
     * @mbggenerated Tue Jun 27 18:44:28 CST 2017
     */
    int countByExample(PrCategoryCriteria example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pr_category
     *
     * @mbggenerated Tue Jun 27 18:44:28 CST 2017
     */
    int deleteByExample(PrCategoryCriteria example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pr_category
     *
     * @mbggenerated Tue Jun 27 18:44:28 CST 2017
     */
    int deleteByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pr_category
     *
     * @mbggenerated Tue Jun 27 18:44:28 CST 2017
     */
    int insert(PrCategory record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pr_category
     *
     * @mbggenerated Tue Jun 27 18:44:28 CST 2017
     */
    int insertSelective(PrCategory record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pr_category
     *
     * @mbggenerated Tue Jun 27 18:44:28 CST 2017
     */
    List<PrCategory> selectByExample(PrCategoryCriteria example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pr_category
     *
     * @mbggenerated Tue Jun 27 18:44:28 CST 2017
     */
    PrCategory selectByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pr_category
     *
     * @mbggenerated Tue Jun 27 18:44:28 CST 2017
     */
    int updateByExampleSelective(@Param("record") PrCategory record, @Param("example") PrCategoryCriteria example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pr_category
     *
     * @mbggenerated Tue Jun 27 18:44:28 CST 2017
     */
    int updateByExample(@Param("record") PrCategory record, @Param("example") PrCategoryCriteria example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pr_category
     *
     * @mbggenerated Tue Jun 27 18:44:28 CST 2017
     */
    int updateByPrimaryKeySelective(PrCategory record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pr_category
     *
     * @mbggenerated Tue Jun 27 18:44:28 CST 2017
     */
    int updateByPrimaryKey(PrCategory record);
}