package com.zwo.modules.mall.dao;

import com.zwo.modules.mall.domain.PrProductPackagePrice;
import com.zwo.modules.mall.domain.PrProductPackagePriceCriteria;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface PrProductPackagePriceMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pr_product_package_price
     *
     * @mbggenerated Sat Aug 05 10:56:51 CST 2017
     */
    int countByExample(PrProductPackagePriceCriteria example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pr_product_package_price
     *
     * @mbggenerated Sat Aug 05 10:56:51 CST 2017
     */
    int deleteByExample(PrProductPackagePriceCriteria example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pr_product_package_price
     *
     * @mbggenerated Sat Aug 05 10:56:51 CST 2017
     */
    int deleteByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pr_product_package_price
     *
     * @mbggenerated Sat Aug 05 10:56:51 CST 2017
     */
    int insert(PrProductPackagePrice record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pr_product_package_price
     *
     * @mbggenerated Sat Aug 05 10:56:51 CST 2017
     */
    int insertSelective(PrProductPackagePrice record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pr_product_package_price
     *
     * @mbggenerated Sat Aug 05 10:56:51 CST 2017
     */
    List<PrProductPackagePrice> selectByExample(PrProductPackagePriceCriteria example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pr_product_package_price
     *
     * @mbggenerated Sat Aug 05 10:56:51 CST 2017
     */
    PrProductPackagePrice selectByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pr_product_package_price
     *
     * @mbggenerated Sat Aug 05 10:56:51 CST 2017
     */
    int updateByExampleSelective(@Param("record") PrProductPackagePrice record, @Param("example") PrProductPackagePriceCriteria example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pr_product_package_price
     *
     * @mbggenerated Sat Aug 05 10:56:51 CST 2017
     */
    int updateByExample(@Param("record") PrProductPackagePrice record, @Param("example") PrProductPackagePriceCriteria example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pr_product_package_price
     *
     * @mbggenerated Sat Aug 05 10:56:51 CST 2017
     */
    int updateByPrimaryKeySelective(PrProductPackagePrice record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pr_product_package_price
     *
     * @mbggenerated Sat Aug 05 10:56:51 CST 2017
     */
    int updateByPrimaryKey(PrProductPackagePrice record);
}