package com.zwo.modules.mall.dao;

import com.zwo.modules.mall.domain.PrProductProperty;
import com.zwo.modules.mall.domain.PrProductPropertyCriteria;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface PrProductPropertyMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pr_product_property
     *
     * @mbggenerated Sat Aug 05 10:56:51 CST 2017
     */
    int countByExample(PrProductPropertyCriteria example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pr_product_property
     *
     * @mbggenerated Sat Aug 05 10:56:51 CST 2017
     */
    int deleteByExample(PrProductPropertyCriteria example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pr_product_property
     *
     * @mbggenerated Sat Aug 05 10:56:51 CST 2017
     */
    int deleteByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pr_product_property
     *
     * @mbggenerated Sat Aug 05 10:56:51 CST 2017
     */
    int insert(PrProductProperty record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pr_product_property
     *
     * @mbggenerated Sat Aug 05 10:56:51 CST 2017
     */
    int insertSelective(PrProductProperty record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pr_product_property
     *
     * @mbggenerated Sat Aug 05 10:56:51 CST 2017
     */
    List<PrProductProperty> selectByExample(PrProductPropertyCriteria example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pr_product_property
     *
     * @mbggenerated Sat Aug 05 10:56:51 CST 2017
     */
    PrProductProperty selectByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pr_product_property
     *
     * @mbggenerated Sat Aug 05 10:56:51 CST 2017
     */
    int updateByExampleSelective(@Param("record") PrProductProperty record, @Param("example") PrProductPropertyCriteria example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pr_product_property
     *
     * @mbggenerated Sat Aug 05 10:56:51 CST 2017
     */
    int updateByExample(@Param("record") PrProductProperty record, @Param("example") PrProductPropertyCriteria example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pr_product_property
     *
     * @mbggenerated Sat Aug 05 10:56:51 CST 2017
     */
    int updateByPrimaryKeySelective(PrProductProperty record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pr_product_property
     *
     * @mbggenerated Sat Aug 05 10:56:51 CST 2017
     */
    int updateByPrimaryKey(PrProductProperty record);
}