package com.zwo.modules.mall.dao;

import com.zwo.modules.mall.domain.PrProductPropertyValue;
import com.zwo.modules.mall.domain.PrProductPropertyValueCriteria;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface PrProductPropertyValueMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pr_product_property_value
     *
     * @mbggenerated Sat Aug 05 10:56:51 CST 2017
     */
    int countByExample(PrProductPropertyValueCriteria example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pr_product_property_value
     *
     * @mbggenerated Sat Aug 05 10:56:51 CST 2017
     */
    int deleteByExample(PrProductPropertyValueCriteria example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pr_product_property_value
     *
     * @mbggenerated Sat Aug 05 10:56:51 CST 2017
     */
    int deleteByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pr_product_property_value
     *
     * @mbggenerated Sat Aug 05 10:56:51 CST 2017
     */
    int insert(PrProductPropertyValue record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pr_product_property_value
     *
     * @mbggenerated Sat Aug 05 10:56:51 CST 2017
     */
    int insertSelective(PrProductPropertyValue record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pr_product_property_value
     *
     * @mbggenerated Sat Aug 05 10:56:51 CST 2017
     */
    List<PrProductPropertyValue> selectByExample(PrProductPropertyValueCriteria example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pr_product_property_value
     *
     * @mbggenerated Sat Aug 05 10:56:51 CST 2017
     */
    PrProductPropertyValue selectByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pr_product_property_value
     *
     * @mbggenerated Sat Aug 05 10:56:51 CST 2017
     */
    int updateByExampleSelective(@Param("record") PrProductPropertyValue record, @Param("example") PrProductPropertyValueCriteria example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pr_product_property_value
     *
     * @mbggenerated Sat Aug 05 10:56:51 CST 2017
     */
    int updateByExample(@Param("record") PrProductPropertyValue record, @Param("example") PrProductPropertyValueCriteria example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pr_product_property_value
     *
     * @mbggenerated Sat Aug 05 10:56:51 CST 2017
     */
    int updateByPrimaryKeySelective(PrProductPropertyValue record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pr_product_property_value
     *
     * @mbggenerated Sat Aug 05 10:56:51 CST 2017
     */
    int updateByPrimaryKey(PrProductPropertyValue record);
}