package com.zwo.modules.member.domain;

import java.io.Serializable;
import java.util.Date;
import org.springframework.format.annotation.DateTimeFormat;

public class GuessCategory implements Serializable {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column guess_category.ID
     *
     * @mbggenerated Wed Aug 02 06:40:52 CST 2017
     */
    private String id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column guess_category.CREATOR
     *
     * @mbggenerated Wed Aug 02 06:40:52 CST 2017
     */
    private String creator;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column guess_category.UPDATER
     *
     * @mbggenerated Wed Aug 02 06:40:52 CST 2017
     */
    private String updater;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column guess_category.ORG_ID
     *
     * @mbggenerated Wed Aug 02 06:40:52 CST 2017
     */
    private String orgId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column guess_category.CREATE_DATE
     *
     * @mbggenerated Wed Aug 02 06:40:52 CST 2017
     */
    private Date createDate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column guess_category.UPDATE_DATE
     *
     * @mbggenerated Wed Aug 02 06:40:52 CST 2017
     */
    private Date updateDate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column guess_category.DISABLE
     *
     * @mbggenerated Wed Aug 02 06:40:52 CST 2017
     */
    private Boolean disable;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column guess_category.START_TIME
     *
     * @mbggenerated Wed Aug 02 06:40:52 CST 2017
     */
    private Date startTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column guess_category.END_TIME
     *
     * @mbggenerated Wed Aug 02 06:40:52 CST 2017
     */
    private Date endTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column guess_category.SORT
     *
     * @mbggenerated Wed Aug 02 06:40:52 CST 2017
     */
    private Integer sort;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column guess_category.IS_DEFAULT
     *
     * @mbggenerated Wed Aug 02 06:40:52 CST 2017
     */
    private Boolean isDefault;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column guess_category.EN_NAME
     *
     * @mbggenerated Wed Aug 02 06:40:52 CST 2017
     */
    private String enName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column guess_category.NAME
     *
     * @mbggenerated Wed Aug 02 06:40:52 CST 2017
     */
    private String name;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column guess_category.DESCRIPTION
     *
     * @mbggenerated Wed Aug 02 06:40:52 CST 2017
     */
    private String description;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column guess_category.PARENT_ID
     *
     * @mbggenerated Wed Aug 02 06:40:52 CST 2017
     */
    private String parentId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column guess_category.PARENTIDS
     *
     * @mbggenerated Wed Aug 02 06:40:52 CST 2017
     */
    private String parentids;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column guess_category.ICON
     *
     * @mbggenerated Wed Aug 02 06:40:52 CST 2017
     */
    private String icon;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column guess_category.KEYWORDS
     *
     * @mbggenerated Wed Aug 02 06:40:52 CST 2017
     */
    private String keywords;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column guess_category.THUMBNAIL
     *
     * @mbggenerated Wed Aug 02 06:40:52 CST 2017
     */
    private String thumbnail;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column guess_category.CODE
     *
     * @mbggenerated Wed Aug 02 06:40:52 CST 2017
     */
    private String code;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column guess_category.USER_ID
     *
     * @mbggenerated Wed Aug 02 06:40:52 CST 2017
     */
    private String userId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table guess_category
     *
     * @mbggenerated Wed Aug 02 06:40:52 CST 2017
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column guess_category.ID
     *
     * @return the value of guess_category.ID
     *
     * @mbggenerated Wed Aug 02 06:40:52 CST 2017
     */
    public String getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column guess_category.ID
     *
     * @param id the value for guess_category.ID
     *
     * @mbggenerated Wed Aug 02 06:40:52 CST 2017
     */
    public void setId(String id) {
        this.id = id == null ? null : id.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column guess_category.CREATOR
     *
     * @return the value of guess_category.CREATOR
     *
     * @mbggenerated Wed Aug 02 06:40:52 CST 2017
     */
    public String getCreator() {
        return creator;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column guess_category.CREATOR
     *
     * @param creator the value for guess_category.CREATOR
     *
     * @mbggenerated Wed Aug 02 06:40:52 CST 2017
     */
    public void setCreator(String creator) {
        this.creator = creator == null ? null : creator.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column guess_category.UPDATER
     *
     * @return the value of guess_category.UPDATER
     *
     * @mbggenerated Wed Aug 02 06:40:52 CST 2017
     */
    public String getUpdater() {
        return updater;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column guess_category.UPDATER
     *
     * @param updater the value for guess_category.UPDATER
     *
     * @mbggenerated Wed Aug 02 06:40:52 CST 2017
     */
    public void setUpdater(String updater) {
        this.updater = updater == null ? null : updater.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column guess_category.ORG_ID
     *
     * @return the value of guess_category.ORG_ID
     *
     * @mbggenerated Wed Aug 02 06:40:52 CST 2017
     */
    public String getOrgId() {
        return orgId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column guess_category.ORG_ID
     *
     * @param orgId the value for guess_category.ORG_ID
     *
     * @mbggenerated Wed Aug 02 06:40:52 CST 2017
     */
    public void setOrgId(String orgId) {
        this.orgId = orgId == null ? null : orgId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column guess_category.CREATE_DATE
     *
     * @return the value of guess_category.CREATE_DATE
     *
     * @mbggenerated Wed Aug 02 06:40:52 CST 2017
     */
    public Date getCreateDate() {
        return createDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column guess_category.CREATE_DATE
     *
     * @param createDate the value for guess_category.CREATE_DATE
     *
     * @mbggenerated Wed Aug 02 06:40:52 CST 2017
     */
    public void setCreateDate(Date createDate) {
        this.createDate = createDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column guess_category.UPDATE_DATE
     *
     * @return the value of guess_category.UPDATE_DATE
     *
     * @mbggenerated Wed Aug 02 06:40:52 CST 2017
     */
    public Date getUpdateDate() {
        return updateDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column guess_category.UPDATE_DATE
     *
     * @param updateDate the value for guess_category.UPDATE_DATE
     *
     * @mbggenerated Wed Aug 02 06:40:52 CST 2017
     */
    public void setUpdateDate(Date updateDate) {
        this.updateDate = updateDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column guess_category.DISABLE
     *
     * @return the value of guess_category.DISABLE
     *
     * @mbggenerated Wed Aug 02 06:40:52 CST 2017
     */
    public Boolean getDisable() {
        return disable;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column guess_category.DISABLE
     *
     * @param disable the value for guess_category.DISABLE
     *
     * @mbggenerated Wed Aug 02 06:40:52 CST 2017
     */
    public void setDisable(Boolean disable) {
        this.disable = disable;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column guess_category.START_TIME
     *
     * @return the value of guess_category.START_TIME
     *
     * @mbggenerated Wed Aug 02 06:40:52 CST 2017
     */
    public Date getStartTime() {
        return startTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column guess_category.START_TIME
     *
     * @param startTime the value for guess_category.START_TIME
     *
     * @mbggenerated Wed Aug 02 06:40:52 CST 2017
     */
    public void setStartTime(Date startTime) {
        this.startTime = startTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column guess_category.END_TIME
     *
     * @return the value of guess_category.END_TIME
     *
     * @mbggenerated Wed Aug 02 06:40:52 CST 2017
     */
    public Date getEndTime() {
        return endTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column guess_category.END_TIME
     *
     * @param endTime the value for guess_category.END_TIME
     *
     * @mbggenerated Wed Aug 02 06:40:52 CST 2017
     */
    public void setEndTime(Date endTime) {
        this.endTime = endTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column guess_category.SORT
     *
     * @return the value of guess_category.SORT
     *
     * @mbggenerated Wed Aug 02 06:40:52 CST 2017
     */
    public Integer getSort() {
        return sort;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column guess_category.SORT
     *
     * @param sort the value for guess_category.SORT
     *
     * @mbggenerated Wed Aug 02 06:40:52 CST 2017
     */
    public void setSort(Integer sort) {
        this.sort = sort;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column guess_category.IS_DEFAULT
     *
     * @return the value of guess_category.IS_DEFAULT
     *
     * @mbggenerated Wed Aug 02 06:40:52 CST 2017
     */
    public Boolean getIsDefault() {
        return isDefault;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column guess_category.IS_DEFAULT
     *
     * @param isDefault the value for guess_category.IS_DEFAULT
     *
     * @mbggenerated Wed Aug 02 06:40:52 CST 2017
     */
    public void setIsDefault(Boolean isDefault) {
        this.isDefault = isDefault;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column guess_category.EN_NAME
     *
     * @return the value of guess_category.EN_NAME
     *
     * @mbggenerated Wed Aug 02 06:40:52 CST 2017
     */
    public String getEnName() {
        return enName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column guess_category.EN_NAME
     *
     * @param enName the value for guess_category.EN_NAME
     *
     * @mbggenerated Wed Aug 02 06:40:52 CST 2017
     */
    public void setEnName(String enName) {
        this.enName = enName == null ? null : enName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column guess_category.NAME
     *
     * @return the value of guess_category.NAME
     *
     * @mbggenerated Wed Aug 02 06:40:52 CST 2017
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column guess_category.NAME
     *
     * @param name the value for guess_category.NAME
     *
     * @mbggenerated Wed Aug 02 06:40:52 CST 2017
     */
    public void setName(String name) {
        this.name = name == null ? null : name.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column guess_category.DESCRIPTION
     *
     * @return the value of guess_category.DESCRIPTION
     *
     * @mbggenerated Wed Aug 02 06:40:52 CST 2017
     */
    public String getDescription() {
        return description;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column guess_category.DESCRIPTION
     *
     * @param description the value for guess_category.DESCRIPTION
     *
     * @mbggenerated Wed Aug 02 06:40:52 CST 2017
     */
    public void setDescription(String description) {
        this.description = description == null ? null : description.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column guess_category.PARENT_ID
     *
     * @return the value of guess_category.PARENT_ID
     *
     * @mbggenerated Wed Aug 02 06:40:52 CST 2017
     */
    public String getParentId() {
        return parentId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column guess_category.PARENT_ID
     *
     * @param parentId the value for guess_category.PARENT_ID
     *
     * @mbggenerated Wed Aug 02 06:40:52 CST 2017
     */
    public void setParentId(String parentId) {
        this.parentId = parentId == null ? null : parentId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column guess_category.PARENTIDS
     *
     * @return the value of guess_category.PARENTIDS
     *
     * @mbggenerated Wed Aug 02 06:40:52 CST 2017
     */
    public String getParentids() {
        return parentids;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column guess_category.PARENTIDS
     *
     * @param parentids the value for guess_category.PARENTIDS
     *
     * @mbggenerated Wed Aug 02 06:40:52 CST 2017
     */
    public void setParentids(String parentids) {
        this.parentids = parentids == null ? null : parentids.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column guess_category.ICON
     *
     * @return the value of guess_category.ICON
     *
     * @mbggenerated Wed Aug 02 06:40:52 CST 2017
     */
    public String getIcon() {
        return icon;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column guess_category.ICON
     *
     * @param icon the value for guess_category.ICON
     *
     * @mbggenerated Wed Aug 02 06:40:52 CST 2017
     */
    public void setIcon(String icon) {
        this.icon = icon == null ? null : icon.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column guess_category.KEYWORDS
     *
     * @return the value of guess_category.KEYWORDS
     *
     * @mbggenerated Wed Aug 02 06:40:52 CST 2017
     */
    public String getKeywords() {
        return keywords;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column guess_category.KEYWORDS
     *
     * @param keywords the value for guess_category.KEYWORDS
     *
     * @mbggenerated Wed Aug 02 06:40:52 CST 2017
     */
    public void setKeywords(String keywords) {
        this.keywords = keywords == null ? null : keywords.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column guess_category.THUMBNAIL
     *
     * @return the value of guess_category.THUMBNAIL
     *
     * @mbggenerated Wed Aug 02 06:40:52 CST 2017
     */
    public String getThumbnail() {
        return thumbnail;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column guess_category.THUMBNAIL
     *
     * @param thumbnail the value for guess_category.THUMBNAIL
     *
     * @mbggenerated Wed Aug 02 06:40:52 CST 2017
     */
    public void setThumbnail(String thumbnail) {
        this.thumbnail = thumbnail == null ? null : thumbnail.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column guess_category.CODE
     *
     * @return the value of guess_category.CODE
     *
     * @mbggenerated Wed Aug 02 06:40:52 CST 2017
     */
    public String getCode() {
        return code;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column guess_category.CODE
     *
     * @param code the value for guess_category.CODE
     *
     * @mbggenerated Wed Aug 02 06:40:52 CST 2017
     */
    public void setCode(String code) {
        this.code = code == null ? null : code.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column guess_category.USER_ID
     *
     * @return the value of guess_category.USER_ID
     *
     * @mbggenerated Wed Aug 02 06:40:52 CST 2017
     */
    public String getUserId() {
        return userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column guess_category.USER_ID
     *
     * @param userId the value for guess_category.USER_ID
     *
     * @mbggenerated Wed Aug 02 06:40:52 CST 2017
     */
    public void setUserId(String userId) {
        this.userId = userId == null ? null : userId.trim();
    }
}