package com.zwo.modules.mall.domain;

import java.io.Serializable;
import java.util.Date;
import org.springframework.format.annotation.DateTimeFormat;

public class OrderTrade implements Serializable {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column order_trade.ID
     *
     * @mbggenerated Thu Aug 10 16:35:55 CST 2017
     */
    private String id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column order_trade.CREATOR
     *
     * @mbggenerated Thu Aug 10 16:35:55 CST 2017
     */
    private String creator;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column order_trade.UPDATER
     *
     * @mbggenerated Thu Aug 10 16:35:55 CST 2017
     */
    private String updater;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column order_trade.ORG_ID
     *
     * @mbggenerated Thu Aug 10 16:35:55 CST 2017
     */
    private String orgId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column order_trade.CREATE_DATE
     *
     * @mbggenerated Thu Aug 10 16:35:55 CST 2017
     */
    private Date createDate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column order_trade.UPDATE_DATE
     *
     * @mbggenerated Thu Aug 10 16:35:55 CST 2017
     */
    private Date updateDate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column order_trade.DISABLE
     *
     * @mbggenerated Thu Aug 10 16:35:55 CST 2017
     */
    private Boolean disable;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column order_trade.START_TIME
     *
     * @mbggenerated Thu Aug 10 16:35:55 CST 2017
     */
    private Date startTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column order_trade.END_TIME
     *
     * @mbggenerated Thu Aug 10 16:35:55 CST 2017
     */
    private Date endTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column order_trade.SORT
     *
     * @mbggenerated Thu Aug 10 16:35:55 CST 2017
     */
    private Integer sort;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column order_trade.IS_DEFAULT
     *
     * @mbggenerated Thu Aug 10 16:35:55 CST 2017
     */
    private Boolean isDefault;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column order_trade.DESCRIPTION
     *
     * @mbggenerated Thu Aug 10 16:35:55 CST 2017
     */
    private String description;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column order_trade.CODE
     *
     * @mbggenerated Thu Aug 10 16:35:55 CST 2017
     */
    private String code;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column order_trade.STATUS
     *
     * @mbggenerated Thu Aug 10 16:35:55 CST 2017
     */
    private String status;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column order_trade.SHOP_ID
     *
     * @mbggenerated Thu Aug 10 16:35:55 CST 2017
     */
    private String shopId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column order_trade.PRODUCT_ID
     *
     * @mbggenerated Thu Aug 10 16:35:55 CST 2017
     */
    private String productId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column order_trade.DEAL_PRICE
     *
     * @mbggenerated Thu Aug 10 16:35:55 CST 2017
     */
    private String dealPrice;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column order_trade.MEMBER_ID
     *
     * @mbggenerated Thu Aug 10 16:35:55 CST 2017
     */
    private String memberId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column order_trade.BUY_NUM
     *
     * @mbggenerated Thu Aug 10 16:35:55 CST 2017
     */
    private Integer buyNum;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column order_trade.RECIVE_NAME
     *
     * @mbggenerated Thu Aug 10 16:35:55 CST 2017
     */
    private String reciveName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column order_trade.ADDRESS
     *
     * @mbggenerated Thu Aug 10 16:35:55 CST 2017
     */
    private String address;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column order_trade.TELEPHONE
     *
     * @mbggenerated Thu Aug 10 16:35:55 CST 2017
     */
    private String telephone;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column order_trade.MAIL_CODE
     *
     * @mbggenerated Thu Aug 10 16:35:55 CST 2017
     */
    private String mailCode;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column order_trade.DELIVERY_COMPANY
     *
     * @mbggenerated Thu Aug 10 16:35:55 CST 2017
     */
    private String deliveryCompany;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column order_trade.DELIVERY_ORDER_CODE
     *
     * @mbggenerated Thu Aug 10 16:35:55 CST 2017
     */
    private String deliveryOrderCode;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column order_trade.IS_FORM_SCCUESS
     *
     * @mbggenerated Thu Aug 10 16:35:55 CST 2017
     */
    private Boolean isFormSccuess;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column order_trade.TRANSPORT_FEE
     *
     * @mbggenerated Thu Aug 10 16:35:55 CST 2017
     */
    private Double transportFee;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table order_trade
     *
     * @mbggenerated Thu Aug 10 16:35:55 CST 2017
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column order_trade.ID
     *
     * @return the value of order_trade.ID
     *
     * @mbggenerated Thu Aug 10 16:35:55 CST 2017
     */
    public String getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column order_trade.ID
     *
     * @param id the value for order_trade.ID
     *
     * @mbggenerated Thu Aug 10 16:35:55 CST 2017
     */
    public void setId(String id) {
        this.id = id == null ? null : id.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column order_trade.CREATOR
     *
     * @return the value of order_trade.CREATOR
     *
     * @mbggenerated Thu Aug 10 16:35:55 CST 2017
     */
    public String getCreator() {
        return creator;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column order_trade.CREATOR
     *
     * @param creator the value for order_trade.CREATOR
     *
     * @mbggenerated Thu Aug 10 16:35:55 CST 2017
     */
    public void setCreator(String creator) {
        this.creator = creator == null ? null : creator.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column order_trade.UPDATER
     *
     * @return the value of order_trade.UPDATER
     *
     * @mbggenerated Thu Aug 10 16:35:55 CST 2017
     */
    public String getUpdater() {
        return updater;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column order_trade.UPDATER
     *
     * @param updater the value for order_trade.UPDATER
     *
     * @mbggenerated Thu Aug 10 16:35:55 CST 2017
     */
    public void setUpdater(String updater) {
        this.updater = updater == null ? null : updater.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column order_trade.ORG_ID
     *
     * @return the value of order_trade.ORG_ID
     *
     * @mbggenerated Thu Aug 10 16:35:55 CST 2017
     */
    public String getOrgId() {
        return orgId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column order_trade.ORG_ID
     *
     * @param orgId the value for order_trade.ORG_ID
     *
     * @mbggenerated Thu Aug 10 16:35:55 CST 2017
     */
    public void setOrgId(String orgId) {
        this.orgId = orgId == null ? null : orgId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column order_trade.CREATE_DATE
     *
     * @return the value of order_trade.CREATE_DATE
     *
     * @mbggenerated Thu Aug 10 16:35:55 CST 2017
     */
    public Date getCreateDate() {
        return createDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column order_trade.CREATE_DATE
     *
     * @param createDate the value for order_trade.CREATE_DATE
     *
     * @mbggenerated Thu Aug 10 16:35:55 CST 2017
     */
    public void setCreateDate(Date createDate) {
        this.createDate = createDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column order_trade.UPDATE_DATE
     *
     * @return the value of order_trade.UPDATE_DATE
     *
     * @mbggenerated Thu Aug 10 16:35:55 CST 2017
     */
    public Date getUpdateDate() {
        return updateDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column order_trade.UPDATE_DATE
     *
     * @param updateDate the value for order_trade.UPDATE_DATE
     *
     * @mbggenerated Thu Aug 10 16:35:55 CST 2017
     */
    public void setUpdateDate(Date updateDate) {
        this.updateDate = updateDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column order_trade.DISABLE
     *
     * @return the value of order_trade.DISABLE
     *
     * @mbggenerated Thu Aug 10 16:35:55 CST 2017
     */
    public Boolean getDisable() {
        return disable;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column order_trade.DISABLE
     *
     * @param disable the value for order_trade.DISABLE
     *
     * @mbggenerated Thu Aug 10 16:35:55 CST 2017
     */
    public void setDisable(Boolean disable) {
        this.disable = disable;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column order_trade.START_TIME
     *
     * @return the value of order_trade.START_TIME
     *
     * @mbggenerated Thu Aug 10 16:35:55 CST 2017
     */
    public Date getStartTime() {
        return startTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column order_trade.START_TIME
     *
     * @param startTime the value for order_trade.START_TIME
     *
     * @mbggenerated Thu Aug 10 16:35:55 CST 2017
     */
    public void setStartTime(Date startTime) {
        this.startTime = startTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column order_trade.END_TIME
     *
     * @return the value of order_trade.END_TIME
     *
     * @mbggenerated Thu Aug 10 16:35:55 CST 2017
     */
    public Date getEndTime() {
        return endTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column order_trade.END_TIME
     *
     * @param endTime the value for order_trade.END_TIME
     *
     * @mbggenerated Thu Aug 10 16:35:55 CST 2017
     */
    public void setEndTime(Date endTime) {
        this.endTime = endTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column order_trade.SORT
     *
     * @return the value of order_trade.SORT
     *
     * @mbggenerated Thu Aug 10 16:35:55 CST 2017
     */
    public Integer getSort() {
        return sort;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column order_trade.SORT
     *
     * @param sort the value for order_trade.SORT
     *
     * @mbggenerated Thu Aug 10 16:35:55 CST 2017
     */
    public void setSort(Integer sort) {
        this.sort = sort;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column order_trade.IS_DEFAULT
     *
     * @return the value of order_trade.IS_DEFAULT
     *
     * @mbggenerated Thu Aug 10 16:35:55 CST 2017
     */
    public Boolean getIsDefault() {
        return isDefault;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column order_trade.IS_DEFAULT
     *
     * @param isDefault the value for order_trade.IS_DEFAULT
     *
     * @mbggenerated Thu Aug 10 16:35:55 CST 2017
     */
    public void setIsDefault(Boolean isDefault) {
        this.isDefault = isDefault;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column order_trade.DESCRIPTION
     *
     * @return the value of order_trade.DESCRIPTION
     *
     * @mbggenerated Thu Aug 10 16:35:55 CST 2017
     */
    public String getDescription() {
        return description;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column order_trade.DESCRIPTION
     *
     * @param description the value for order_trade.DESCRIPTION
     *
     * @mbggenerated Thu Aug 10 16:35:55 CST 2017
     */
    public void setDescription(String description) {
        this.description = description == null ? null : description.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column order_trade.CODE
     *
     * @return the value of order_trade.CODE
     *
     * @mbggenerated Thu Aug 10 16:35:55 CST 2017
     */
    public String getCode() {
        return code;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column order_trade.CODE
     *
     * @param code the value for order_trade.CODE
     *
     * @mbggenerated Thu Aug 10 16:35:55 CST 2017
     */
    public void setCode(String code) {
        this.code = code == null ? null : code.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column order_trade.STATUS
     *
     * @return the value of order_trade.STATUS
     *
     * @mbggenerated Thu Aug 10 16:35:55 CST 2017
     */
    public String getStatus() {
        return status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column order_trade.STATUS
     *
     * @param status the value for order_trade.STATUS
     *
     * @mbggenerated Thu Aug 10 16:35:55 CST 2017
     */
    public void setStatus(String status) {
        this.status = status == null ? null : status.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column order_trade.SHOP_ID
     *
     * @return the value of order_trade.SHOP_ID
     *
     * @mbggenerated Thu Aug 10 16:35:55 CST 2017
     */
    public String getShopId() {
        return shopId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column order_trade.SHOP_ID
     *
     * @param shopId the value for order_trade.SHOP_ID
     *
     * @mbggenerated Thu Aug 10 16:35:55 CST 2017
     */
    public void setShopId(String shopId) {
        this.shopId = shopId == null ? null : shopId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column order_trade.PRODUCT_ID
     *
     * @return the value of order_trade.PRODUCT_ID
     *
     * @mbggenerated Thu Aug 10 16:35:55 CST 2017
     */
    public String getProductId() {
        return productId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column order_trade.PRODUCT_ID
     *
     * @param productId the value for order_trade.PRODUCT_ID
     *
     * @mbggenerated Thu Aug 10 16:35:55 CST 2017
     */
    public void setProductId(String productId) {
        this.productId = productId == null ? null : productId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column order_trade.DEAL_PRICE
     *
     * @return the value of order_trade.DEAL_PRICE
     *
     * @mbggenerated Thu Aug 10 16:35:55 CST 2017
     */
    public String getDealPrice() {
        return dealPrice;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column order_trade.DEAL_PRICE
     *
     * @param dealPrice the value for order_trade.DEAL_PRICE
     *
     * @mbggenerated Thu Aug 10 16:35:55 CST 2017
     */
    public void setDealPrice(String dealPrice) {
        this.dealPrice = dealPrice == null ? null : dealPrice.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column order_trade.MEMBER_ID
     *
     * @return the value of order_trade.MEMBER_ID
     *
     * @mbggenerated Thu Aug 10 16:35:55 CST 2017
     */
    public String getMemberId() {
        return memberId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column order_trade.MEMBER_ID
     *
     * @param memberId the value for order_trade.MEMBER_ID
     *
     * @mbggenerated Thu Aug 10 16:35:55 CST 2017
     */
    public void setMemberId(String memberId) {
        this.memberId = memberId == null ? null : memberId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column order_trade.BUY_NUM
     *
     * @return the value of order_trade.BUY_NUM
     *
     * @mbggenerated Thu Aug 10 16:35:55 CST 2017
     */
    public Integer getBuyNum() {
        return buyNum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column order_trade.BUY_NUM
     *
     * @param buyNum the value for order_trade.BUY_NUM
     *
     * @mbggenerated Thu Aug 10 16:35:55 CST 2017
     */
    public void setBuyNum(Integer buyNum) {
        this.buyNum = buyNum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column order_trade.RECIVE_NAME
     *
     * @return the value of order_trade.RECIVE_NAME
     *
     * @mbggenerated Thu Aug 10 16:35:55 CST 2017
     */
    public String getReciveName() {
        return reciveName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column order_trade.RECIVE_NAME
     *
     * @param reciveName the value for order_trade.RECIVE_NAME
     *
     * @mbggenerated Thu Aug 10 16:35:55 CST 2017
     */
    public void setReciveName(String reciveName) {
        this.reciveName = reciveName == null ? null : reciveName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column order_trade.ADDRESS
     *
     * @return the value of order_trade.ADDRESS
     *
     * @mbggenerated Thu Aug 10 16:35:55 CST 2017
     */
    public String getAddress() {
        return address;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column order_trade.ADDRESS
     *
     * @param address the value for order_trade.ADDRESS
     *
     * @mbggenerated Thu Aug 10 16:35:55 CST 2017
     */
    public void setAddress(String address) {
        this.address = address == null ? null : address.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column order_trade.TELEPHONE
     *
     * @return the value of order_trade.TELEPHONE
     *
     * @mbggenerated Thu Aug 10 16:35:55 CST 2017
     */
    public String getTelephone() {
        return telephone;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column order_trade.TELEPHONE
     *
     * @param telephone the value for order_trade.TELEPHONE
     *
     * @mbggenerated Thu Aug 10 16:35:55 CST 2017
     */
    public void setTelephone(String telephone) {
        this.telephone = telephone == null ? null : telephone.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column order_trade.MAIL_CODE
     *
     * @return the value of order_trade.MAIL_CODE
     *
     * @mbggenerated Thu Aug 10 16:35:55 CST 2017
     */
    public String getMailCode() {
        return mailCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column order_trade.MAIL_CODE
     *
     * @param mailCode the value for order_trade.MAIL_CODE
     *
     * @mbggenerated Thu Aug 10 16:35:55 CST 2017
     */
    public void setMailCode(String mailCode) {
        this.mailCode = mailCode == null ? null : mailCode.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column order_trade.DELIVERY_COMPANY
     *
     * @return the value of order_trade.DELIVERY_COMPANY
     *
     * @mbggenerated Thu Aug 10 16:35:55 CST 2017
     */
    public String getDeliveryCompany() {
        return deliveryCompany;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column order_trade.DELIVERY_COMPANY
     *
     * @param deliveryCompany the value for order_trade.DELIVERY_COMPANY
     *
     * @mbggenerated Thu Aug 10 16:35:55 CST 2017
     */
    public void setDeliveryCompany(String deliveryCompany) {
        this.deliveryCompany = deliveryCompany == null ? null : deliveryCompany.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column order_trade.DELIVERY_ORDER_CODE
     *
     * @return the value of order_trade.DELIVERY_ORDER_CODE
     *
     * @mbggenerated Thu Aug 10 16:35:55 CST 2017
     */
    public String getDeliveryOrderCode() {
        return deliveryOrderCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column order_trade.DELIVERY_ORDER_CODE
     *
     * @param deliveryOrderCode the value for order_trade.DELIVERY_ORDER_CODE
     *
     * @mbggenerated Thu Aug 10 16:35:55 CST 2017
     */
    public void setDeliveryOrderCode(String deliveryOrderCode) {
        this.deliveryOrderCode = deliveryOrderCode == null ? null : deliveryOrderCode.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column order_trade.IS_FORM_SCCUESS
     *
     * @return the value of order_trade.IS_FORM_SCCUESS
     *
     * @mbggenerated Thu Aug 10 16:35:55 CST 2017
     */
    public Boolean getIsFormSccuess() {
        return isFormSccuess;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column order_trade.IS_FORM_SCCUESS
     *
     * @param isFormSccuess the value for order_trade.IS_FORM_SCCUESS
     *
     * @mbggenerated Thu Aug 10 16:35:55 CST 2017
     */
    public void setIsFormSccuess(Boolean isFormSccuess) {
        this.isFormSccuess = isFormSccuess;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column order_trade.TRANSPORT_FEE
     *
     * @return the value of order_trade.TRANSPORT_FEE
     *
     * @mbggenerated Thu Aug 10 16:35:55 CST 2017
     */
    public Double getTransportFee() {
        return transportFee;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column order_trade.TRANSPORT_FEE
     *
     * @param transportFee the value for order_trade.TRANSPORT_FEE
     *
     * @mbggenerated Thu Aug 10 16:35:55 CST 2017
     */
    public void setTransportFee(Double transportFee) {
        this.transportFee = transportFee;
    }
}