package com.zwo.modules.payment.domain;

import java.io.Serializable;
import java.util.Date;
import org.springframework.format.annotation.DateTimeFormat;

public class PayTradePaymentOrder implements Serializable {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pay_trade_payment_order.ID
     *
     * @mbggenerated Wed Aug 02 07:04:04 CST 2017
     */
    private String id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pay_trade_payment_order.CREATOR
     *
     * @mbggenerated Wed Aug 02 07:04:04 CST 2017
     */
    private String creator;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pay_trade_payment_order.UPDATER
     *
     * @mbggenerated Wed Aug 02 07:04:04 CST 2017
     */
    private String updater;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pay_trade_payment_order.CREATE_DATE
     *
     * @mbggenerated Wed Aug 02 07:04:04 CST 2017
     */
    private Date createDate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pay_trade_payment_order.UPDATE_DATE
     *
     * @mbggenerated Wed Aug 02 07:04:04 CST 2017
     */
    private Date updateDate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pay_trade_payment_order.DISABLE
     *
     * @mbggenerated Wed Aug 02 07:04:04 CST 2017
     */
    private Boolean disable;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pay_trade_payment_order.START_TIME
     *
     * @mbggenerated Wed Aug 02 07:04:04 CST 2017
     */
    private Date startTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pay_trade_payment_order.END_TIME
     *
     * @mbggenerated Wed Aug 02 07:04:04 CST 2017
     */
    private Date endTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pay_trade_payment_order.SORT
     *
     * @mbggenerated Wed Aug 02 07:04:04 CST 2017
     */
    private Integer sort;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pay_trade_payment_order.MEMBER_ID
     *
     * @mbggenerated Wed Aug 02 07:04:04 CST 2017
     */
    private String memberId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pay_trade_payment_order.ORDER_ID
     *
     * @mbggenerated Wed Aug 02 07:04:04 CST 2017
     */
    private String orderId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pay_trade_payment_order.PRODUCT_ID
     *
     * @mbggenerated Wed Aug 02 07:04:04 CST 2017
     */
    private String productId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pay_trade_payment_order.ORG_ID
     *
     * @mbggenerated Wed Aug 02 07:04:04 CST 2017
     */
    private String orgId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pay_trade_payment_order.MEM_NAME
     *
     * @mbggenerated Wed Aug 02 07:04:04 CST 2017
     */
    private String memName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pay_trade_payment_order.DESCRIPTION
     *
     * @mbggenerated Wed Aug 02 07:04:04 CST 2017
     */
    private String description;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pay_trade_payment_order.STATUS
     *
     * @mbggenerated Wed Aug 02 07:04:04 CST 2017
     */
    private String status;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pay_trade_payment_order.PRODUCT_NAME
     *
     * @mbggenerated Wed Aug 02 07:04:04 CST 2017
     */
    private String productName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pay_trade_payment_order.ORDER_AMOUNT
     *
     * @mbggenerated Wed Aug 02 07:04:04 CST 2017
     */
    private Double orderAmount;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pay_trade_payment_order.MERCHANT_ORDER_NO
     *
     * @mbggenerated Wed Aug 02 07:04:04 CST 2017
     */
    private String merchantOrderNo;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pay_trade_payment_order.ORDER_FROM
     *
     * @mbggenerated Wed Aug 02 07:04:04 CST 2017
     */
    private String orderFrom;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pay_trade_payment_order.MERCHANT_NAME
     *
     * @mbggenerated Wed Aug 02 07:04:04 CST 2017
     */
    private String merchantName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pay_trade_payment_order.MERCHANT_NO
     *
     * @mbggenerated Wed Aug 02 07:04:04 CST 2017
     */
    private String merchantNo;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pay_trade_payment_order.ORDER_TIME
     *
     * @mbggenerated Wed Aug 02 07:04:04 CST 2017
     */
    private Date orderTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pay_trade_payment_order.ORDER_DATE
     *
     * @mbggenerated Wed Aug 02 07:04:04 CST 2017
     */
    private Date orderDate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pay_trade_payment_order.ORDER_IP
     *
     * @mbggenerated Wed Aug 02 07:04:04 CST 2017
     */
    private String orderIp;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pay_trade_payment_order.ORDER_REFERER_URL
     *
     * @mbggenerated Wed Aug 02 07:04:04 CST 2017
     */
    private String orderRefererUrl;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pay_trade_payment_order.RETURN_URL
     *
     * @mbggenerated Wed Aug 02 07:04:04 CST 2017
     */
    private String returnUrl;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pay_trade_payment_order.NOTIFY_URL
     *
     * @mbggenerated Wed Aug 02 07:04:04 CST 2017
     */
    private String notifyUrl;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pay_trade_payment_order.CANCEL_REASON
     *
     * @mbggenerated Wed Aug 02 07:04:04 CST 2017
     */
    private String cancelReason;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pay_trade_payment_order.ORDER_PERIOD
     *
     * @mbggenerated Wed Aug 02 07:04:04 CST 2017
     */
    private Integer orderPeriod;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pay_trade_payment_order.EXPIRE_TIME
     *
     * @mbggenerated Wed Aug 02 07:04:04 CST 2017
     */
    private Date expireTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pay_trade_payment_order.REMARK
     *
     * @mbggenerated Wed Aug 02 07:04:04 CST 2017
     */
    private String remark;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pay_trade_payment_order.PAY_WAY_NAME
     *
     * @mbggenerated Wed Aug 02 07:04:04 CST 2017
     */
    private String payWayName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pay_trade_payment_order.PAY_WAY_CODE
     *
     * @mbggenerated Wed Aug 02 07:04:04 CST 2017
     */
    private String payWayCode;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pay_trade_payment_order.TRX_TYPE
     *
     * @mbggenerated Wed Aug 02 07:04:04 CST 2017
     */
    private String trxType;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pay_trade_payment_order.TRX_NO
     *
     * @mbggenerated Wed Aug 02 07:04:04 CST 2017
     */
    private String trxNo;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pay_trade_payment_order.PAY_TYPE_CODE
     *
     * @mbggenerated Wed Aug 02 07:04:04 CST 2017
     */
    private String payTypeCode;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pay_trade_payment_order.PAY_TYPE_NAME
     *
     * @mbggenerated Wed Aug 02 07:04:04 CST 2017
     */
    private String payTypeName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pay_trade_payment_order.FUND_INTO_TYPE
     *
     * @mbggenerated Wed Aug 02 07:04:04 CST 2017
     */
    private String fundIntoType;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pay_trade_payment_order.IS_REFUND
     *
     * @mbggenerated Wed Aug 02 07:04:04 CST 2017
     */
    private Boolean isRefund;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pay_trade_payment_order.REFUND_TIMES
     *
     * @mbggenerated Wed Aug 02 07:04:04 CST 2017
     */
    private Integer refundTimes;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table pay_trade_payment_order
     *
     * @mbggenerated Wed Aug 02 07:04:04 CST 2017
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column pay_trade_payment_order.ID
     *
     * @return the value of pay_trade_payment_order.ID
     *
     * @mbggenerated Wed Aug 02 07:04:04 CST 2017
     */
    public String getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column pay_trade_payment_order.ID
     *
     * @param id the value for pay_trade_payment_order.ID
     *
     * @mbggenerated Wed Aug 02 07:04:04 CST 2017
     */
    public void setId(String id) {
        this.id = id == null ? null : id.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column pay_trade_payment_order.CREATOR
     *
     * @return the value of pay_trade_payment_order.CREATOR
     *
     * @mbggenerated Wed Aug 02 07:04:04 CST 2017
     */
    public String getCreator() {
        return creator;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column pay_trade_payment_order.CREATOR
     *
     * @param creator the value for pay_trade_payment_order.CREATOR
     *
     * @mbggenerated Wed Aug 02 07:04:04 CST 2017
     */
    public void setCreator(String creator) {
        this.creator = creator == null ? null : creator.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column pay_trade_payment_order.UPDATER
     *
     * @return the value of pay_trade_payment_order.UPDATER
     *
     * @mbggenerated Wed Aug 02 07:04:04 CST 2017
     */
    public String getUpdater() {
        return updater;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column pay_trade_payment_order.UPDATER
     *
     * @param updater the value for pay_trade_payment_order.UPDATER
     *
     * @mbggenerated Wed Aug 02 07:04:04 CST 2017
     */
    public void setUpdater(String updater) {
        this.updater = updater == null ? null : updater.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column pay_trade_payment_order.CREATE_DATE
     *
     * @return the value of pay_trade_payment_order.CREATE_DATE
     *
     * @mbggenerated Wed Aug 02 07:04:04 CST 2017
     */
    public Date getCreateDate() {
        return createDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column pay_trade_payment_order.CREATE_DATE
     *
     * @param createDate the value for pay_trade_payment_order.CREATE_DATE
     *
     * @mbggenerated Wed Aug 02 07:04:04 CST 2017
     */
    public void setCreateDate(Date createDate) {
        this.createDate = createDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column pay_trade_payment_order.UPDATE_DATE
     *
     * @return the value of pay_trade_payment_order.UPDATE_DATE
     *
     * @mbggenerated Wed Aug 02 07:04:04 CST 2017
     */
    public Date getUpdateDate() {
        return updateDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column pay_trade_payment_order.UPDATE_DATE
     *
     * @param updateDate the value for pay_trade_payment_order.UPDATE_DATE
     *
     * @mbggenerated Wed Aug 02 07:04:04 CST 2017
     */
    public void setUpdateDate(Date updateDate) {
        this.updateDate = updateDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column pay_trade_payment_order.DISABLE
     *
     * @return the value of pay_trade_payment_order.DISABLE
     *
     * @mbggenerated Wed Aug 02 07:04:04 CST 2017
     */
    public Boolean getDisable() {
        return disable;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column pay_trade_payment_order.DISABLE
     *
     * @param disable the value for pay_trade_payment_order.DISABLE
     *
     * @mbggenerated Wed Aug 02 07:04:04 CST 2017
     */
    public void setDisable(Boolean disable) {
        this.disable = disable;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column pay_trade_payment_order.START_TIME
     *
     * @return the value of pay_trade_payment_order.START_TIME
     *
     * @mbggenerated Wed Aug 02 07:04:04 CST 2017
     */
    public Date getStartTime() {
        return startTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column pay_trade_payment_order.START_TIME
     *
     * @param startTime the value for pay_trade_payment_order.START_TIME
     *
     * @mbggenerated Wed Aug 02 07:04:04 CST 2017
     */
    public void setStartTime(Date startTime) {
        this.startTime = startTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column pay_trade_payment_order.END_TIME
     *
     * @return the value of pay_trade_payment_order.END_TIME
     *
     * @mbggenerated Wed Aug 02 07:04:04 CST 2017
     */
    public Date getEndTime() {
        return endTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column pay_trade_payment_order.END_TIME
     *
     * @param endTime the value for pay_trade_payment_order.END_TIME
     *
     * @mbggenerated Wed Aug 02 07:04:04 CST 2017
     */
    public void setEndTime(Date endTime) {
        this.endTime = endTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column pay_trade_payment_order.SORT
     *
     * @return the value of pay_trade_payment_order.SORT
     *
     * @mbggenerated Wed Aug 02 07:04:04 CST 2017
     */
    public Integer getSort() {
        return sort;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column pay_trade_payment_order.SORT
     *
     * @param sort the value for pay_trade_payment_order.SORT
     *
     * @mbggenerated Wed Aug 02 07:04:04 CST 2017
     */
    public void setSort(Integer sort) {
        this.sort = sort;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column pay_trade_payment_order.MEMBER_ID
     *
     * @return the value of pay_trade_payment_order.MEMBER_ID
     *
     * @mbggenerated Wed Aug 02 07:04:04 CST 2017
     */
    public String getMemberId() {
        return memberId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column pay_trade_payment_order.MEMBER_ID
     *
     * @param memberId the value for pay_trade_payment_order.MEMBER_ID
     *
     * @mbggenerated Wed Aug 02 07:04:04 CST 2017
     */
    public void setMemberId(String memberId) {
        this.memberId = memberId == null ? null : memberId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column pay_trade_payment_order.ORDER_ID
     *
     * @return the value of pay_trade_payment_order.ORDER_ID
     *
     * @mbggenerated Wed Aug 02 07:04:04 CST 2017
     */
    public String getOrderId() {
        return orderId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column pay_trade_payment_order.ORDER_ID
     *
     * @param orderId the value for pay_trade_payment_order.ORDER_ID
     *
     * @mbggenerated Wed Aug 02 07:04:04 CST 2017
     */
    public void setOrderId(String orderId) {
        this.orderId = orderId == null ? null : orderId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column pay_trade_payment_order.PRODUCT_ID
     *
     * @return the value of pay_trade_payment_order.PRODUCT_ID
     *
     * @mbggenerated Wed Aug 02 07:04:04 CST 2017
     */
    public String getProductId() {
        return productId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column pay_trade_payment_order.PRODUCT_ID
     *
     * @param productId the value for pay_trade_payment_order.PRODUCT_ID
     *
     * @mbggenerated Wed Aug 02 07:04:04 CST 2017
     */
    public void setProductId(String productId) {
        this.productId = productId == null ? null : productId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column pay_trade_payment_order.ORG_ID
     *
     * @return the value of pay_trade_payment_order.ORG_ID
     *
     * @mbggenerated Wed Aug 02 07:04:04 CST 2017
     */
    public String getOrgId() {
        return orgId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column pay_trade_payment_order.ORG_ID
     *
     * @param orgId the value for pay_trade_payment_order.ORG_ID
     *
     * @mbggenerated Wed Aug 02 07:04:04 CST 2017
     */
    public void setOrgId(String orgId) {
        this.orgId = orgId == null ? null : orgId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column pay_trade_payment_order.MEM_NAME
     *
     * @return the value of pay_trade_payment_order.MEM_NAME
     *
     * @mbggenerated Wed Aug 02 07:04:04 CST 2017
     */
    public String getMemName() {
        return memName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column pay_trade_payment_order.MEM_NAME
     *
     * @param memName the value for pay_trade_payment_order.MEM_NAME
     *
     * @mbggenerated Wed Aug 02 07:04:04 CST 2017
     */
    public void setMemName(String memName) {
        this.memName = memName == null ? null : memName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column pay_trade_payment_order.DESCRIPTION
     *
     * @return the value of pay_trade_payment_order.DESCRIPTION
     *
     * @mbggenerated Wed Aug 02 07:04:04 CST 2017
     */
    public String getDescription() {
        return description;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column pay_trade_payment_order.DESCRIPTION
     *
     * @param description the value for pay_trade_payment_order.DESCRIPTION
     *
     * @mbggenerated Wed Aug 02 07:04:04 CST 2017
     */
    public void setDescription(String description) {
        this.description = description == null ? null : description.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column pay_trade_payment_order.STATUS
     *
     * @return the value of pay_trade_payment_order.STATUS
     *
     * @mbggenerated Wed Aug 02 07:04:04 CST 2017
     */
    public String getStatus() {
        return status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column pay_trade_payment_order.STATUS
     *
     * @param status the value for pay_trade_payment_order.STATUS
     *
     * @mbggenerated Wed Aug 02 07:04:04 CST 2017
     */
    public void setStatus(String status) {
        this.status = status == null ? null : status.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column pay_trade_payment_order.PRODUCT_NAME
     *
     * @return the value of pay_trade_payment_order.PRODUCT_NAME
     *
     * @mbggenerated Wed Aug 02 07:04:04 CST 2017
     */
    public String getProductName() {
        return productName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column pay_trade_payment_order.PRODUCT_NAME
     *
     * @param productName the value for pay_trade_payment_order.PRODUCT_NAME
     *
     * @mbggenerated Wed Aug 02 07:04:04 CST 2017
     */
    public void setProductName(String productName) {
        this.productName = productName == null ? null : productName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column pay_trade_payment_order.ORDER_AMOUNT
     *
     * @return the value of pay_trade_payment_order.ORDER_AMOUNT
     *
     * @mbggenerated Wed Aug 02 07:04:04 CST 2017
     */
    public Double getOrderAmount() {
        return orderAmount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column pay_trade_payment_order.ORDER_AMOUNT
     *
     * @param orderAmount the value for pay_trade_payment_order.ORDER_AMOUNT
     *
     * @mbggenerated Wed Aug 02 07:04:04 CST 2017
     */
    public void setOrderAmount(Double orderAmount) {
        this.orderAmount = orderAmount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column pay_trade_payment_order.MERCHANT_ORDER_NO
     *
     * @return the value of pay_trade_payment_order.MERCHANT_ORDER_NO
     *
     * @mbggenerated Wed Aug 02 07:04:04 CST 2017
     */
    public String getMerchantOrderNo() {
        return merchantOrderNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column pay_trade_payment_order.MERCHANT_ORDER_NO
     *
     * @param merchantOrderNo the value for pay_trade_payment_order.MERCHANT_ORDER_NO
     *
     * @mbggenerated Wed Aug 02 07:04:04 CST 2017
     */
    public void setMerchantOrderNo(String merchantOrderNo) {
        this.merchantOrderNo = merchantOrderNo == null ? null : merchantOrderNo.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column pay_trade_payment_order.ORDER_FROM
     *
     * @return the value of pay_trade_payment_order.ORDER_FROM
     *
     * @mbggenerated Wed Aug 02 07:04:04 CST 2017
     */
    public String getOrderFrom() {
        return orderFrom;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column pay_trade_payment_order.ORDER_FROM
     *
     * @param orderFrom the value for pay_trade_payment_order.ORDER_FROM
     *
     * @mbggenerated Wed Aug 02 07:04:04 CST 2017
     */
    public void setOrderFrom(String orderFrom) {
        this.orderFrom = orderFrom == null ? null : orderFrom.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column pay_trade_payment_order.MERCHANT_NAME
     *
     * @return the value of pay_trade_payment_order.MERCHANT_NAME
     *
     * @mbggenerated Wed Aug 02 07:04:04 CST 2017
     */
    public String getMerchantName() {
        return merchantName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column pay_trade_payment_order.MERCHANT_NAME
     *
     * @param merchantName the value for pay_trade_payment_order.MERCHANT_NAME
     *
     * @mbggenerated Wed Aug 02 07:04:04 CST 2017
     */
    public void setMerchantName(String merchantName) {
        this.merchantName = merchantName == null ? null : merchantName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column pay_trade_payment_order.MERCHANT_NO
     *
     * @return the value of pay_trade_payment_order.MERCHANT_NO
     *
     * @mbggenerated Wed Aug 02 07:04:04 CST 2017
     */
    public String getMerchantNo() {
        return merchantNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column pay_trade_payment_order.MERCHANT_NO
     *
     * @param merchantNo the value for pay_trade_payment_order.MERCHANT_NO
     *
     * @mbggenerated Wed Aug 02 07:04:04 CST 2017
     */
    public void setMerchantNo(String merchantNo) {
        this.merchantNo = merchantNo == null ? null : merchantNo.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column pay_trade_payment_order.ORDER_TIME
     *
     * @return the value of pay_trade_payment_order.ORDER_TIME
     *
     * @mbggenerated Wed Aug 02 07:04:04 CST 2017
     */
    public Date getOrderTime() {
        return orderTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column pay_trade_payment_order.ORDER_TIME
     *
     * @param orderTime the value for pay_trade_payment_order.ORDER_TIME
     *
     * @mbggenerated Wed Aug 02 07:04:04 CST 2017
     */
    public void setOrderTime(Date orderTime) {
        this.orderTime = orderTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column pay_trade_payment_order.ORDER_DATE
     *
     * @return the value of pay_trade_payment_order.ORDER_DATE
     *
     * @mbggenerated Wed Aug 02 07:04:04 CST 2017
     */
    public Date getOrderDate() {
        return orderDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column pay_trade_payment_order.ORDER_DATE
     *
     * @param orderDate the value for pay_trade_payment_order.ORDER_DATE
     *
     * @mbggenerated Wed Aug 02 07:04:04 CST 2017
     */
    public void setOrderDate(Date orderDate) {
        this.orderDate = orderDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column pay_trade_payment_order.ORDER_IP
     *
     * @return the value of pay_trade_payment_order.ORDER_IP
     *
     * @mbggenerated Wed Aug 02 07:04:04 CST 2017
     */
    public String getOrderIp() {
        return orderIp;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column pay_trade_payment_order.ORDER_IP
     *
     * @param orderIp the value for pay_trade_payment_order.ORDER_IP
     *
     * @mbggenerated Wed Aug 02 07:04:04 CST 2017
     */
    public void setOrderIp(String orderIp) {
        this.orderIp = orderIp == null ? null : orderIp.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column pay_trade_payment_order.ORDER_REFERER_URL
     *
     * @return the value of pay_trade_payment_order.ORDER_REFERER_URL
     *
     * @mbggenerated Wed Aug 02 07:04:04 CST 2017
     */
    public String getOrderRefererUrl() {
        return orderRefererUrl;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column pay_trade_payment_order.ORDER_REFERER_URL
     *
     * @param orderRefererUrl the value for pay_trade_payment_order.ORDER_REFERER_URL
     *
     * @mbggenerated Wed Aug 02 07:04:04 CST 2017
     */
    public void setOrderRefererUrl(String orderRefererUrl) {
        this.orderRefererUrl = orderRefererUrl == null ? null : orderRefererUrl.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column pay_trade_payment_order.RETURN_URL
     *
     * @return the value of pay_trade_payment_order.RETURN_URL
     *
     * @mbggenerated Wed Aug 02 07:04:04 CST 2017
     */
    public String getReturnUrl() {
        return returnUrl;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column pay_trade_payment_order.RETURN_URL
     *
     * @param returnUrl the value for pay_trade_payment_order.RETURN_URL
     *
     * @mbggenerated Wed Aug 02 07:04:04 CST 2017
     */
    public void setReturnUrl(String returnUrl) {
        this.returnUrl = returnUrl == null ? null : returnUrl.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column pay_trade_payment_order.NOTIFY_URL
     *
     * @return the value of pay_trade_payment_order.NOTIFY_URL
     *
     * @mbggenerated Wed Aug 02 07:04:04 CST 2017
     */
    public String getNotifyUrl() {
        return notifyUrl;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column pay_trade_payment_order.NOTIFY_URL
     *
     * @param notifyUrl the value for pay_trade_payment_order.NOTIFY_URL
     *
     * @mbggenerated Wed Aug 02 07:04:04 CST 2017
     */
    public void setNotifyUrl(String notifyUrl) {
        this.notifyUrl = notifyUrl == null ? null : notifyUrl.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column pay_trade_payment_order.CANCEL_REASON
     *
     * @return the value of pay_trade_payment_order.CANCEL_REASON
     *
     * @mbggenerated Wed Aug 02 07:04:04 CST 2017
     */
    public String getCancelReason() {
        return cancelReason;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column pay_trade_payment_order.CANCEL_REASON
     *
     * @param cancelReason the value for pay_trade_payment_order.CANCEL_REASON
     *
     * @mbggenerated Wed Aug 02 07:04:04 CST 2017
     */
    public void setCancelReason(String cancelReason) {
        this.cancelReason = cancelReason == null ? null : cancelReason.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column pay_trade_payment_order.ORDER_PERIOD
     *
     * @return the value of pay_trade_payment_order.ORDER_PERIOD
     *
     * @mbggenerated Wed Aug 02 07:04:04 CST 2017
     */
    public Integer getOrderPeriod() {
        return orderPeriod;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column pay_trade_payment_order.ORDER_PERIOD
     *
     * @param orderPeriod the value for pay_trade_payment_order.ORDER_PERIOD
     *
     * @mbggenerated Wed Aug 02 07:04:04 CST 2017
     */
    public void setOrderPeriod(Integer orderPeriod) {
        this.orderPeriod = orderPeriod;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column pay_trade_payment_order.EXPIRE_TIME
     *
     * @return the value of pay_trade_payment_order.EXPIRE_TIME
     *
     * @mbggenerated Wed Aug 02 07:04:04 CST 2017
     */
    public Date getExpireTime() {
        return expireTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column pay_trade_payment_order.EXPIRE_TIME
     *
     * @param expireTime the value for pay_trade_payment_order.EXPIRE_TIME
     *
     * @mbggenerated Wed Aug 02 07:04:04 CST 2017
     */
    public void setExpireTime(Date expireTime) {
        this.expireTime = expireTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column pay_trade_payment_order.REMARK
     *
     * @return the value of pay_trade_payment_order.REMARK
     *
     * @mbggenerated Wed Aug 02 07:04:04 CST 2017
     */
    public String getRemark() {
        return remark;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column pay_trade_payment_order.REMARK
     *
     * @param remark the value for pay_trade_payment_order.REMARK
     *
     * @mbggenerated Wed Aug 02 07:04:04 CST 2017
     */
    public void setRemark(String remark) {
        this.remark = remark == null ? null : remark.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column pay_trade_payment_order.PAY_WAY_NAME
     *
     * @return the value of pay_trade_payment_order.PAY_WAY_NAME
     *
     * @mbggenerated Wed Aug 02 07:04:04 CST 2017
     */
    public String getPayWayName() {
        return payWayName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column pay_trade_payment_order.PAY_WAY_NAME
     *
     * @param payWayName the value for pay_trade_payment_order.PAY_WAY_NAME
     *
     * @mbggenerated Wed Aug 02 07:04:04 CST 2017
     */
    public void setPayWayName(String payWayName) {
        this.payWayName = payWayName == null ? null : payWayName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column pay_trade_payment_order.PAY_WAY_CODE
     *
     * @return the value of pay_trade_payment_order.PAY_WAY_CODE
     *
     * @mbggenerated Wed Aug 02 07:04:04 CST 2017
     */
    public String getPayWayCode() {
        return payWayCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column pay_trade_payment_order.PAY_WAY_CODE
     *
     * @param payWayCode the value for pay_trade_payment_order.PAY_WAY_CODE
     *
     * @mbggenerated Wed Aug 02 07:04:04 CST 2017
     */
    public void setPayWayCode(String payWayCode) {
        this.payWayCode = payWayCode == null ? null : payWayCode.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column pay_trade_payment_order.TRX_TYPE
     *
     * @return the value of pay_trade_payment_order.TRX_TYPE
     *
     * @mbggenerated Wed Aug 02 07:04:04 CST 2017
     */
    public String getTrxType() {
        return trxType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column pay_trade_payment_order.TRX_TYPE
     *
     * @param trxType the value for pay_trade_payment_order.TRX_TYPE
     *
     * @mbggenerated Wed Aug 02 07:04:04 CST 2017
     */
    public void setTrxType(String trxType) {
        this.trxType = trxType == null ? null : trxType.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column pay_trade_payment_order.TRX_NO
     *
     * @return the value of pay_trade_payment_order.TRX_NO
     *
     * @mbggenerated Wed Aug 02 07:04:04 CST 2017
     */
    public String getTrxNo() {
        return trxNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column pay_trade_payment_order.TRX_NO
     *
     * @param trxNo the value for pay_trade_payment_order.TRX_NO
     *
     * @mbggenerated Wed Aug 02 07:04:04 CST 2017
     */
    public void setTrxNo(String trxNo) {
        this.trxNo = trxNo == null ? null : trxNo.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column pay_trade_payment_order.PAY_TYPE_CODE
     *
     * @return the value of pay_trade_payment_order.PAY_TYPE_CODE
     *
     * @mbggenerated Wed Aug 02 07:04:04 CST 2017
     */
    public String getPayTypeCode() {
        return payTypeCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column pay_trade_payment_order.PAY_TYPE_CODE
     *
     * @param payTypeCode the value for pay_trade_payment_order.PAY_TYPE_CODE
     *
     * @mbggenerated Wed Aug 02 07:04:04 CST 2017
     */
    public void setPayTypeCode(String payTypeCode) {
        this.payTypeCode = payTypeCode == null ? null : payTypeCode.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column pay_trade_payment_order.PAY_TYPE_NAME
     *
     * @return the value of pay_trade_payment_order.PAY_TYPE_NAME
     *
     * @mbggenerated Wed Aug 02 07:04:04 CST 2017
     */
    public String getPayTypeName() {
        return payTypeName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column pay_trade_payment_order.PAY_TYPE_NAME
     *
     * @param payTypeName the value for pay_trade_payment_order.PAY_TYPE_NAME
     *
     * @mbggenerated Wed Aug 02 07:04:04 CST 2017
     */
    public void setPayTypeName(String payTypeName) {
        this.payTypeName = payTypeName == null ? null : payTypeName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column pay_trade_payment_order.FUND_INTO_TYPE
     *
     * @return the value of pay_trade_payment_order.FUND_INTO_TYPE
     *
     * @mbggenerated Wed Aug 02 07:04:04 CST 2017
     */
    public String getFundIntoType() {
        return fundIntoType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column pay_trade_payment_order.FUND_INTO_TYPE
     *
     * @param fundIntoType the value for pay_trade_payment_order.FUND_INTO_TYPE
     *
     * @mbggenerated Wed Aug 02 07:04:04 CST 2017
     */
    public void setFundIntoType(String fundIntoType) {
        this.fundIntoType = fundIntoType == null ? null : fundIntoType.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column pay_trade_payment_order.IS_REFUND
     *
     * @return the value of pay_trade_payment_order.IS_REFUND
     *
     * @mbggenerated Wed Aug 02 07:04:04 CST 2017
     */
    public Boolean getIsRefund() {
        return isRefund;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column pay_trade_payment_order.IS_REFUND
     *
     * @param isRefund the value for pay_trade_payment_order.IS_REFUND
     *
     * @mbggenerated Wed Aug 02 07:04:04 CST 2017
     */
    public void setIsRefund(Boolean isRefund) {
        this.isRefund = isRefund;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column pay_trade_payment_order.REFUND_TIMES
     *
     * @return the value of pay_trade_payment_order.REFUND_TIMES
     *
     * @mbggenerated Wed Aug 02 07:04:04 CST 2017
     */
    public Integer getRefundTimes() {
        return refundTimes;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column pay_trade_payment_order.REFUND_TIMES
     *
     * @param refundTimes the value for pay_trade_payment_order.REFUND_TIMES
     *
     * @mbggenerated Wed Aug 02 07:04:04 CST 2017
     */
    public void setRefundTimes(Integer refundTimes) {
        this.refundTimes = refundTimes;
    }
}