package com.zwo.modules.shop.dao;

import com.zwo.modules.shop.domain.Shop;
import com.zwo.modules.shop.domain.ShopCriteria;
import com.zwo.modules.shop.domain.ShopWithBLOBs;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface ShopMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table shop
     *
     * @mbggenerated Tue Aug 01 19:17:35 CST 2017
     */
    int countByExample(ShopCriteria example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table shop
     *
     * @mbggenerated Tue Aug 01 19:17:35 CST 2017
     */
    int deleteByExample(ShopCriteria example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table shop
     *
     * @mbggenerated Tue Aug 01 19:17:35 CST 2017
     */
    int deleteByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table shop
     *
     * @mbggenerated Tue Aug 01 19:17:35 CST 2017
     */
    int insert(ShopWithBLOBs record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table shop
     *
     * @mbggenerated Tue Aug 01 19:17:35 CST 2017
     */
    int insertSelective(ShopWithBLOBs record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table shop
     *
     * @mbggenerated Tue Aug 01 19:17:35 CST 2017
     */
    List<ShopWithBLOBs> selectByExampleWithBLOBs(ShopCriteria example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table shop
     *
     * @mbggenerated Tue Aug 01 19:17:35 CST 2017
     */
    List<Shop> selectByExample(ShopCriteria example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table shop
     *
     * @mbggenerated Tue Aug 01 19:17:35 CST 2017
     */
    ShopWithBLOBs selectByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table shop
     *
     * @mbggenerated Tue Aug 01 19:17:35 CST 2017
     */
    int updateByExampleSelective(@Param("record") ShopWithBLOBs record, @Param("example") ShopCriteria example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table shop
     *
     * @mbggenerated Tue Aug 01 19:17:35 CST 2017
     */
    int updateByExampleWithBLOBs(@Param("record") ShopWithBLOBs record, @Param("example") ShopCriteria example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table shop
     *
     * @mbggenerated Tue Aug 01 19:17:35 CST 2017
     */
    int updateByExample(@Param("record") Shop record, @Param("example") ShopCriteria example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table shop
     *
     * @mbggenerated Tue Aug 01 19:17:35 CST 2017
     */
    int updateByPrimaryKeySelective(ShopWithBLOBs record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table shop
     *
     * @mbggenerated Tue Aug 01 19:17:35 CST 2017
     */
    int updateByPrimaryKeyWithBLOBs(ShopWithBLOBs record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table shop
     *
     * @mbggenerated Tue Aug 01 19:17:35 CST 2017
     */
    int updateByPrimaryKey(Shop record);
}