package com.fulan.application.achievement.domain;

import java.io.Serializable;
import java.util.Date;

public class FwdAgentInfo implements Serializable {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column fwd_agent_info.ID
     *
     * @mbggenerated Wed May 23 17:26:10 CST 2018
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column fwd_agent_info.AGENT_CODE
     *
     * @mbggenerated Wed May 23 17:26:10 CST 2018
     */
    private String agentCode;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column fwd_agent_info.CREATE_DATETIME
     *
     * @mbggenerated Wed May 23 17:26:10 CST 2018
     */
    private Date createDatetime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column fwd_agent_info.UPDATE_DATETIME
     *
     * @mbggenerated Wed May 23 17:26:10 CST 2018
     */
    private Date updateDatetime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column fwd_agent_info.DESCRIPTION
     *
     * @mbggenerated Wed May 23 17:26:10 CST 2018
     */
    private String description;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column fwd_agent_info.NAME
     *
     * @mbggenerated Wed May 23 17:26:10 CST 2018
     */
    private String name;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column fwd_agent_info.IS_DEFAULT
     *
     * @mbggenerated Wed May 23 17:26:10 CST 2018
     */
    private Boolean isDefault;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column fwd_agent_info.PATH
     *
     * @mbggenerated Wed May 23 17:26:10 CST 2018
     */
    private String path;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column fwd_agent_info.URL
     *
     * @mbggenerated Wed May 23 17:26:10 CST 2018
     */
    private String url;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table fwd_agent_info
     *
     * @mbggenerated Wed May 23 17:26:10 CST 2018
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column fwd_agent_info.ID
     *
     * @return the value of fwd_agent_info.ID
     *
     * @mbggenerated Wed May 23 17:26:10 CST 2018
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column fwd_agent_info.ID
     *
     * @param id the value for fwd_agent_info.ID
     *
     * @mbggenerated Wed May 23 17:26:10 CST 2018
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column fwd_agent_info.AGENT_CODE
     *
     * @return the value of fwd_agent_info.AGENT_CODE
     *
     * @mbggenerated Wed May 23 17:26:10 CST 2018
     */
    public String getAgentCode() {
        return agentCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column fwd_agent_info.AGENT_CODE
     *
     * @param agentCode the value for fwd_agent_info.AGENT_CODE
     *
     * @mbggenerated Wed May 23 17:26:10 CST 2018
     */
    public void setAgentCode(String agentCode) {
        this.agentCode = agentCode == null ? null : agentCode.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column fwd_agent_info.CREATE_DATETIME
     *
     * @return the value of fwd_agent_info.CREATE_DATETIME
     *
     * @mbggenerated Wed May 23 17:26:10 CST 2018
     */
    public Date getCreateDatetime() {
        return createDatetime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column fwd_agent_info.CREATE_DATETIME
     *
     * @param createDatetime the value for fwd_agent_info.CREATE_DATETIME
     *
     * @mbggenerated Wed May 23 17:26:10 CST 2018
     */
    public void setCreateDatetime(Date createDatetime) {
        this.createDatetime = createDatetime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column fwd_agent_info.UPDATE_DATETIME
     *
     * @return the value of fwd_agent_info.UPDATE_DATETIME
     *
     * @mbggenerated Wed May 23 17:26:10 CST 2018
     */
    public Date getUpdateDatetime() {
        return updateDatetime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column fwd_agent_info.UPDATE_DATETIME
     *
     * @param updateDatetime the value for fwd_agent_info.UPDATE_DATETIME
     *
     * @mbggenerated Wed May 23 17:26:10 CST 2018
     */
    public void setUpdateDatetime(Date updateDatetime) {
        this.updateDatetime = updateDatetime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column fwd_agent_info.DESCRIPTION
     *
     * @return the value of fwd_agent_info.DESCRIPTION
     *
     * @mbggenerated Wed May 23 17:26:10 CST 2018
     */
    public String getDescription() {
        return description;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column fwd_agent_info.DESCRIPTION
     *
     * @param description the value for fwd_agent_info.DESCRIPTION
     *
     * @mbggenerated Wed May 23 17:26:10 CST 2018
     */
    public void setDescription(String description) {
        this.description = description == null ? null : description.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column fwd_agent_info.NAME
     *
     * @return the value of fwd_agent_info.NAME
     *
     * @mbggenerated Wed May 23 17:26:10 CST 2018
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column fwd_agent_info.NAME
     *
     * @param name the value for fwd_agent_info.NAME
     *
     * @mbggenerated Wed May 23 17:26:10 CST 2018
     */
    public void setName(String name) {
        this.name = name == null ? null : name.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column fwd_agent_info.IS_DEFAULT
     *
     * @return the value of fwd_agent_info.IS_DEFAULT
     *
     * @mbggenerated Wed May 23 17:26:10 CST 2018
     */
    public Boolean getIsDefault() {
        return isDefault;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column fwd_agent_info.IS_DEFAULT
     *
     * @param isDefault the value for fwd_agent_info.IS_DEFAULT
     *
     * @mbggenerated Wed May 23 17:26:10 CST 2018
     */
    public void setIsDefault(Boolean isDefault) {
        this.isDefault = isDefault;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column fwd_agent_info.PATH
     *
     * @return the value of fwd_agent_info.PATH
     *
     * @mbggenerated Wed May 23 17:26:10 CST 2018
     */
    public String getPath() {
        return path;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column fwd_agent_info.PATH
     *
     * @param path the value for fwd_agent_info.PATH
     *
     * @mbggenerated Wed May 23 17:26:10 CST 2018
     */
    public void setPath(String path) {
        this.path = path == null ? null : path.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column fwd_agent_info.URL
     *
     * @return the value of fwd_agent_info.URL
     *
     * @mbggenerated Wed May 23 17:26:10 CST 2018
     */
    public String getUrl() {
        return url;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column fwd_agent_info.URL
     *
     * @param url the value for fwd_agent_info.URL
     *
     * @mbggenerated Wed May 23 17:26:10 CST 2018
     */
    public void setUrl(String url) {
        this.url = url == null ? null : url.trim();
    }
}