package com.fulan.application.oa.domain;

import java.util.ArrayList;
import java.util.Date;
import java.util.List;

public class FwdOaApplyFormExample {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table fwd_oa_apply_form
     *
     * @mbggenerated Mon Jun 04 14:47:17 CST 2018
     */
    protected String orderByClause;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table fwd_oa_apply_form
     *
     * @mbggenerated Mon Jun 04 14:47:17 CST 2018
     */
    protected boolean distinct;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table fwd_oa_apply_form
     *
     * @mbggenerated Mon Jun 04 14:47:17 CST 2018
     */
    protected List<Criteria> oredCriteria;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table fwd_oa_apply_form
     *
     * @mbggenerated Mon Jun 04 14:47:17 CST 2018
     */
    public FwdOaApplyFormExample() {
        oredCriteria = new ArrayList<Criteria>();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table fwd_oa_apply_form
     *
     * @mbggenerated Mon Jun 04 14:47:17 CST 2018
     */
    public void setOrderByClause(String orderByClause) {
        this.orderByClause = orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table fwd_oa_apply_form
     *
     * @mbggenerated Mon Jun 04 14:47:17 CST 2018
     */
    public String getOrderByClause() {
        return orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table fwd_oa_apply_form
     *
     * @mbggenerated Mon Jun 04 14:47:17 CST 2018
     */
    public void setDistinct(boolean distinct) {
        this.distinct = distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table fwd_oa_apply_form
     *
     * @mbggenerated Mon Jun 04 14:47:17 CST 2018
     */
    public boolean isDistinct() {
        return distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table fwd_oa_apply_form
     *
     * @mbggenerated Mon Jun 04 14:47:17 CST 2018
     */
    public List<Criteria> getOredCriteria() {
        return oredCriteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table fwd_oa_apply_form
     *
     * @mbggenerated Mon Jun 04 14:47:17 CST 2018
     */
    public void or(Criteria criteria) {
        oredCriteria.add(criteria);
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table fwd_oa_apply_form
     *
     * @mbggenerated Mon Jun 04 14:47:17 CST 2018
     */
    public Criteria or() {
        Criteria criteria = createCriteriaInternal();
        oredCriteria.add(criteria);
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table fwd_oa_apply_form
     *
     * @mbggenerated Mon Jun 04 14:47:17 CST 2018
     */
    public Criteria createCriteria() {
        Criteria criteria = createCriteriaInternal();
        if (oredCriteria.size() == 0) {
            oredCriteria.add(criteria);
        }
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table fwd_oa_apply_form
     *
     * @mbggenerated Mon Jun 04 14:47:17 CST 2018
     */
    protected Criteria createCriteriaInternal() {
        Criteria criteria = new Criteria();
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table fwd_oa_apply_form
     *
     * @mbggenerated Mon Jun 04 14:47:17 CST 2018
     */
    public void clear() {
        oredCriteria.clear();
        orderByClause = null;
        distinct = false;
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table fwd_oa_apply_form
     *
     * @mbggenerated Mon Jun 04 14:47:17 CST 2018
     */
    protected abstract static class GeneratedCriteria {
        protected List<Criterion> criteria;

        protected GeneratedCriteria() {
            super();
            criteria = new ArrayList<Criterion>();
        }

        public boolean isValid() {
            return criteria.size() > 0;
        }

        public List<Criterion> getAllCriteria() {
            return criteria;
        }

        public List<Criterion> getCriteria() {
            return criteria;
        }

        protected void addCriterion(String condition) {
            if (condition == null) {
                throw new RuntimeException("Value for condition cannot be null");
            }
            criteria.add(new Criterion(condition));
        }

        protected void addCriterion(String condition, Object value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value));
        }

        protected void addCriterion(String condition, Object value1, Object value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value1, value2));
        }

        public Criteria andIdIsNull() {
            addCriterion("ID is null");
            return (Criteria) this;
        }

        public Criteria andIdIsNotNull() {
            addCriterion("ID is not null");
            return (Criteria) this;
        }

        public Criteria andIdEqualTo(Integer value) {
            addCriterion("ID =", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotEqualTo(Integer value) {
            addCriterion("ID <>", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdGreaterThan(Integer value) {
            addCriterion("ID >", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdGreaterThanOrEqualTo(Integer value) {
            addCriterion("ID >=", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdLessThan(Integer value) {
            addCriterion("ID <", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdLessThanOrEqualTo(Integer value) {
            addCriterion("ID <=", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdIn(List<Integer> values) {
            addCriterion("ID in", values, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotIn(List<Integer> values) {
            addCriterion("ID not in", values, "id");
            return (Criteria) this;
        }

        public Criteria andIdBetween(Integer value1, Integer value2) {
            addCriterion("ID between", value1, value2, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotBetween(Integer value1, Integer value2) {
            addCriterion("ID not between", value1, value2, "id");
            return (Criteria) this;
        }

        public Criteria andDescriptionIsNull() {
            addCriterion("DESCRIPTION is null");
            return (Criteria) this;
        }

        public Criteria andDescriptionIsNotNull() {
            addCriterion("DESCRIPTION is not null");
            return (Criteria) this;
        }

        public Criteria andDescriptionEqualTo(String value) {
            addCriterion("DESCRIPTION =", value, "description");
            return (Criteria) this;
        }

        public Criteria andDescriptionNotEqualTo(String value) {
            addCriterion("DESCRIPTION <>", value, "description");
            return (Criteria) this;
        }

        public Criteria andDescriptionGreaterThan(String value) {
            addCriterion("DESCRIPTION >", value, "description");
            return (Criteria) this;
        }

        public Criteria andDescriptionGreaterThanOrEqualTo(String value) {
            addCriterion("DESCRIPTION >=", value, "description");
            return (Criteria) this;
        }

        public Criteria andDescriptionLessThan(String value) {
            addCriterion("DESCRIPTION <", value, "description");
            return (Criteria) this;
        }

        public Criteria andDescriptionLessThanOrEqualTo(String value) {
            addCriterion("DESCRIPTION <=", value, "description");
            return (Criteria) this;
        }

        public Criteria andDescriptionLike(String value) {
            addCriterion("DESCRIPTION like", value, "description");
            return (Criteria) this;
        }

        public Criteria andDescriptionNotLike(String value) {
            addCriterion("DESCRIPTION not like", value, "description");
            return (Criteria) this;
        }

        public Criteria andDescriptionIn(List<String> values) {
            addCriterion("DESCRIPTION in", values, "description");
            return (Criteria) this;
        }

        public Criteria andDescriptionNotIn(List<String> values) {
            addCriterion("DESCRIPTION not in", values, "description");
            return (Criteria) this;
        }

        public Criteria andDescriptionBetween(String value1, String value2) {
            addCriterion("DESCRIPTION between", value1, value2, "description");
            return (Criteria) this;
        }

        public Criteria andDescriptionNotBetween(String value1, String value2) {
            addCriterion("DESCRIPTION not between", value1, value2, "description");
            return (Criteria) this;
        }

        public Criteria andTypeIsNull() {
            addCriterion("TYPE is null");
            return (Criteria) this;
        }

        public Criteria andTypeIsNotNull() {
            addCriterion("TYPE is not null");
            return (Criteria) this;
        }

        public Criteria andTypeEqualTo(String value) {
            addCriterion("TYPE =", value, "type");
            return (Criteria) this;
        }

        public Criteria andTypeNotEqualTo(String value) {
            addCriterion("TYPE <>", value, "type");
            return (Criteria) this;
        }

        public Criteria andTypeGreaterThan(String value) {
            addCriterion("TYPE >", value, "type");
            return (Criteria) this;
        }

        public Criteria andTypeGreaterThanOrEqualTo(String value) {
            addCriterion("TYPE >=", value, "type");
            return (Criteria) this;
        }

        public Criteria andTypeLessThan(String value) {
            addCriterion("TYPE <", value, "type");
            return (Criteria) this;
        }

        public Criteria andTypeLessThanOrEqualTo(String value) {
            addCriterion("TYPE <=", value, "type");
            return (Criteria) this;
        }

        public Criteria andTypeLike(String value) {
            addCriterion("TYPE like", value, "type");
            return (Criteria) this;
        }

        public Criteria andTypeNotLike(String value) {
            addCriterion("TYPE not like", value, "type");
            return (Criteria) this;
        }

        public Criteria andTypeIn(List<String> values) {
            addCriterion("TYPE in", values, "type");
            return (Criteria) this;
        }

        public Criteria andTypeNotIn(List<String> values) {
            addCriterion("TYPE not in", values, "type");
            return (Criteria) this;
        }

        public Criteria andTypeBetween(String value1, String value2) {
            addCriterion("TYPE between", value1, value2, "type");
            return (Criteria) this;
        }

        public Criteria andTypeNotBetween(String value1, String value2) {
            addCriterion("TYPE not between", value1, value2, "type");
            return (Criteria) this;
        }

        public Criteria andAgentCodeIsNull() {
            addCriterion("AGENT_CODE is null");
            return (Criteria) this;
        }

        public Criteria andAgentCodeIsNotNull() {
            addCriterion("AGENT_CODE is not null");
            return (Criteria) this;
        }

        public Criteria andAgentCodeEqualTo(String value) {
            addCriterion("AGENT_CODE =", value, "agentCode");
            return (Criteria) this;
        }

        public Criteria andAgentCodeNotEqualTo(String value) {
            addCriterion("AGENT_CODE <>", value, "agentCode");
            return (Criteria) this;
        }

        public Criteria andAgentCodeGreaterThan(String value) {
            addCriterion("AGENT_CODE >", value, "agentCode");
            return (Criteria) this;
        }

        public Criteria andAgentCodeGreaterThanOrEqualTo(String value) {
            addCriterion("AGENT_CODE >=", value, "agentCode");
            return (Criteria) this;
        }

        public Criteria andAgentCodeLessThan(String value) {
            addCriterion("AGENT_CODE <", value, "agentCode");
            return (Criteria) this;
        }

        public Criteria andAgentCodeLessThanOrEqualTo(String value) {
            addCriterion("AGENT_CODE <=", value, "agentCode");
            return (Criteria) this;
        }

        public Criteria andAgentCodeLike(String value) {
            addCriterion("AGENT_CODE like", value, "agentCode");
            return (Criteria) this;
        }

        public Criteria andAgentCodeNotLike(String value) {
            addCriterion("AGENT_CODE not like", value, "agentCode");
            return (Criteria) this;
        }

        public Criteria andAgentCodeIn(List<String> values) {
            addCriterion("AGENT_CODE in", values, "agentCode");
            return (Criteria) this;
        }

        public Criteria andAgentCodeNotIn(List<String> values) {
            addCriterion("AGENT_CODE not in", values, "agentCode");
            return (Criteria) this;
        }

        public Criteria andAgentCodeBetween(String value1, String value2) {
            addCriterion("AGENT_CODE between", value1, value2, "agentCode");
            return (Criteria) this;
        }

        public Criteria andAgentCodeNotBetween(String value1, String value2) {
            addCriterion("AGENT_CODE not between", value1, value2, "agentCode");
            return (Criteria) this;
        }

        public Criteria andCreateDatetimeIsNull() {
            addCriterion("CREATE_DATETIME is null");
            return (Criteria) this;
        }

        public Criteria andCreateDatetimeIsNotNull() {
            addCriterion("CREATE_DATETIME is not null");
            return (Criteria) this;
        }

        public Criteria andCreateDatetimeEqualTo(Date value) {
            addCriterion("CREATE_DATETIME =", value, "createDatetime");
            return (Criteria) this;
        }

        public Criteria andCreateDatetimeNotEqualTo(Date value) {
            addCriterion("CREATE_DATETIME <>", value, "createDatetime");
            return (Criteria) this;
        }

        public Criteria andCreateDatetimeGreaterThan(Date value) {
            addCriterion("CREATE_DATETIME >", value, "createDatetime");
            return (Criteria) this;
        }

        public Criteria andCreateDatetimeGreaterThanOrEqualTo(Date value) {
            addCriterion("CREATE_DATETIME >=", value, "createDatetime");
            return (Criteria) this;
        }

        public Criteria andCreateDatetimeLessThan(Date value) {
            addCriterion("CREATE_DATETIME <", value, "createDatetime");
            return (Criteria) this;
        }

        public Criteria andCreateDatetimeLessThanOrEqualTo(Date value) {
            addCriterion("CREATE_DATETIME <=", value, "createDatetime");
            return (Criteria) this;
        }

        public Criteria andCreateDatetimeIn(List<Date> values) {
            addCriterion("CREATE_DATETIME in", values, "createDatetime");
            return (Criteria) this;
        }

        public Criteria andCreateDatetimeNotIn(List<Date> values) {
            addCriterion("CREATE_DATETIME not in", values, "createDatetime");
            return (Criteria) this;
        }

        public Criteria andCreateDatetimeBetween(Date value1, Date value2) {
            addCriterion("CREATE_DATETIME between", value1, value2, "createDatetime");
            return (Criteria) this;
        }

        public Criteria andCreateDatetimeNotBetween(Date value1, Date value2) {
            addCriterion("CREATE_DATETIME not between", value1, value2, "createDatetime");
            return (Criteria) this;
        }

        public Criteria andStatusIsNull() {
            addCriterion("STATUS is null");
            return (Criteria) this;
        }

        public Criteria andStatusIsNotNull() {
            addCriterion("STATUS is not null");
            return (Criteria) this;
        }

        public Criteria andStatusEqualTo(Integer value) {
            addCriterion("STATUS =", value, "status");
            return (Criteria) this;
        }

        public Criteria andStatusNotEqualTo(Integer value) {
            addCriterion("STATUS <>", value, "status");
            return (Criteria) this;
        }

        public Criteria andStatusGreaterThan(Integer value) {
            addCriterion("STATUS >", value, "status");
            return (Criteria) this;
        }

        public Criteria andStatusGreaterThanOrEqualTo(Integer value) {
            addCriterion("STATUS >=", value, "status");
            return (Criteria) this;
        }

        public Criteria andStatusLessThan(Integer value) {
            addCriterion("STATUS <", value, "status");
            return (Criteria) this;
        }

        public Criteria andStatusLessThanOrEqualTo(Integer value) {
            addCriterion("STATUS <=", value, "status");
            return (Criteria) this;
        }

        public Criteria andStatusIn(List<Integer> values) {
            addCriterion("STATUS in", values, "status");
            return (Criteria) this;
        }

        public Criteria andStatusNotIn(List<Integer> values) {
            addCriterion("STATUS not in", values, "status");
            return (Criteria) this;
        }

        public Criteria andStatusBetween(Integer value1, Integer value2) {
            addCriterion("STATUS between", value1, value2, "status");
            return (Criteria) this;
        }

        public Criteria andStatusNotBetween(Integer value1, Integer value2) {
            addCriterion("STATUS not between", value1, value2, "status");
            return (Criteria) this;
        }

        public Criteria andStartTimeIsNull() {
            addCriterion("START_TIME is null");
            return (Criteria) this;
        }

        public Criteria andStartTimeIsNotNull() {
            addCriterion("START_TIME is not null");
            return (Criteria) this;
        }

        public Criteria andStartTimeEqualTo(Date value) {
            addCriterion("START_TIME =", value, "startTime");
            return (Criteria) this;
        }

        public Criteria andStartTimeNotEqualTo(Date value) {
            addCriterion("START_TIME <>", value, "startTime");
            return (Criteria) this;
        }

        public Criteria andStartTimeGreaterThan(Date value) {
            addCriterion("START_TIME >", value, "startTime");
            return (Criteria) this;
        }

        public Criteria andStartTimeGreaterThanOrEqualTo(Date value) {
            addCriterion("START_TIME >=", value, "startTime");
            return (Criteria) this;
        }

        public Criteria andStartTimeLessThan(Date value) {
            addCriterion("START_TIME <", value, "startTime");
            return (Criteria) this;
        }

        public Criteria andStartTimeLessThanOrEqualTo(Date value) {
            addCriterion("START_TIME <=", value, "startTime");
            return (Criteria) this;
        }

        public Criteria andStartTimeIn(List<Date> values) {
            addCriterion("START_TIME in", values, "startTime");
            return (Criteria) this;
        }

        public Criteria andStartTimeNotIn(List<Date> values) {
            addCriterion("START_TIME not in", values, "startTime");
            return (Criteria) this;
        }

        public Criteria andStartTimeBetween(Date value1, Date value2) {
            addCriterion("START_TIME between", value1, value2, "startTime");
            return (Criteria) this;
        }

        public Criteria andStartTimeNotBetween(Date value1, Date value2) {
            addCriterion("START_TIME not between", value1, value2, "startTime");
            return (Criteria) this;
        }

        public Criteria andEndTimeIsNull() {
            addCriterion("END_TIME is null");
            return (Criteria) this;
        }

        public Criteria andEndTimeIsNotNull() {
            addCriterion("END_TIME is not null");
            return (Criteria) this;
        }

        public Criteria andEndTimeEqualTo(Date value) {
            addCriterion("END_TIME =", value, "endTime");
            return (Criteria) this;
        }

        public Criteria andEndTimeNotEqualTo(Date value) {
            addCriterion("END_TIME <>", value, "endTime");
            return (Criteria) this;
        }

        public Criteria andEndTimeGreaterThan(Date value) {
            addCriterion("END_TIME >", value, "endTime");
            return (Criteria) this;
        }

        public Criteria andEndTimeGreaterThanOrEqualTo(Date value) {
            addCriterion("END_TIME >=", value, "endTime");
            return (Criteria) this;
        }

        public Criteria andEndTimeLessThan(Date value) {
            addCriterion("END_TIME <", value, "endTime");
            return (Criteria) this;
        }

        public Criteria andEndTimeLessThanOrEqualTo(Date value) {
            addCriterion("END_TIME <=", value, "endTime");
            return (Criteria) this;
        }

        public Criteria andEndTimeIn(List<Date> values) {
            addCriterion("END_TIME in", values, "endTime");
            return (Criteria) this;
        }

        public Criteria andEndTimeNotIn(List<Date> values) {
            addCriterion("END_TIME not in", values, "endTime");
            return (Criteria) this;
        }

        public Criteria andEndTimeBetween(Date value1, Date value2) {
            addCriterion("END_TIME between", value1, value2, "endTime");
            return (Criteria) this;
        }

        public Criteria andEndTimeNotBetween(Date value1, Date value2) {
            addCriterion("END_TIME not between", value1, value2, "endTime");
            return (Criteria) this;
        }

        public Criteria andEndDatetimeIsNull() {
            addCriterion("END_DATETIME is null");
            return (Criteria) this;
        }

        public Criteria andEndDatetimeIsNotNull() {
            addCriterion("END_DATETIME is not null");
            return (Criteria) this;
        }

        public Criteria andEndDatetimeEqualTo(Date value) {
            addCriterion("END_DATETIME =", value, "endDatetime");
            return (Criteria) this;
        }

        public Criteria andEndDatetimeNotEqualTo(Date value) {
            addCriterion("END_DATETIME <>", value, "endDatetime");
            return (Criteria) this;
        }

        public Criteria andEndDatetimeGreaterThan(Date value) {
            addCriterion("END_DATETIME >", value, "endDatetime");
            return (Criteria) this;
        }

        public Criteria andEndDatetimeGreaterThanOrEqualTo(Date value) {
            addCriterion("END_DATETIME >=", value, "endDatetime");
            return (Criteria) this;
        }

        public Criteria andEndDatetimeLessThan(Date value) {
            addCriterion("END_DATETIME <", value, "endDatetime");
            return (Criteria) this;
        }

        public Criteria andEndDatetimeLessThanOrEqualTo(Date value) {
            addCriterion("END_DATETIME <=", value, "endDatetime");
            return (Criteria) this;
        }

        public Criteria andEndDatetimeIn(List<Date> values) {
            addCriterion("END_DATETIME in", values, "endDatetime");
            return (Criteria) this;
        }

        public Criteria andEndDatetimeNotIn(List<Date> values) {
            addCriterion("END_DATETIME not in", values, "endDatetime");
            return (Criteria) this;
        }

        public Criteria andEndDatetimeBetween(Date value1, Date value2) {
            addCriterion("END_DATETIME between", value1, value2, "endDatetime");
            return (Criteria) this;
        }

        public Criteria andEndDatetimeNotBetween(Date value1, Date value2) {
            addCriterion("END_DATETIME not between", value1, value2, "endDatetime");
            return (Criteria) this;
        }

        public Criteria andLeaveTypeIsNull() {
            addCriterion("LEAVE_TYPE is null");
            return (Criteria) this;
        }

        public Criteria andLeaveTypeIsNotNull() {
            addCriterion("LEAVE_TYPE is not null");
            return (Criteria) this;
        }

        public Criteria andLeaveTypeEqualTo(Integer value) {
            addCriterion("LEAVE_TYPE =", value, "leaveType");
            return (Criteria) this;
        }

        public Criteria andLeaveTypeNotEqualTo(Integer value) {
            addCriterion("LEAVE_TYPE <>", value, "leaveType");
            return (Criteria) this;
        }

        public Criteria andLeaveTypeGreaterThan(Integer value) {
            addCriterion("LEAVE_TYPE >", value, "leaveType");
            return (Criteria) this;
        }

        public Criteria andLeaveTypeGreaterThanOrEqualTo(Integer value) {
            addCriterion("LEAVE_TYPE >=", value, "leaveType");
            return (Criteria) this;
        }

        public Criteria andLeaveTypeLessThan(Integer value) {
            addCriterion("LEAVE_TYPE <", value, "leaveType");
            return (Criteria) this;
        }

        public Criteria andLeaveTypeLessThanOrEqualTo(Integer value) {
            addCriterion("LEAVE_TYPE <=", value, "leaveType");
            return (Criteria) this;
        }

        public Criteria andLeaveTypeIn(List<Integer> values) {
            addCriterion("LEAVE_TYPE in", values, "leaveType");
            return (Criteria) this;
        }

        public Criteria andLeaveTypeNotIn(List<Integer> values) {
            addCriterion("LEAVE_TYPE not in", values, "leaveType");
            return (Criteria) this;
        }

        public Criteria andLeaveTypeBetween(Integer value1, Integer value2) {
            addCriterion("LEAVE_TYPE between", value1, value2, "leaveType");
            return (Criteria) this;
        }

        public Criteria andLeaveTypeNotBetween(Integer value1, Integer value2) {
            addCriterion("LEAVE_TYPE not between", value1, value2, "leaveType");
            return (Criteria) this;
        }

        public Criteria andLeaveOffIsNull() {
            addCriterion("LEAVE_OFF is null");
            return (Criteria) this;
        }

        public Criteria andLeaveOffIsNotNull() {
            addCriterion("LEAVE_OFF is not null");
            return (Criteria) this;
        }

        public Criteria andLeaveOffEqualTo(String value) {
            addCriterion("LEAVE_OFF =", value, "leaveOff");
            return (Criteria) this;
        }

        public Criteria andLeaveOffNotEqualTo(String value) {
            addCriterion("LEAVE_OFF <>", value, "leaveOff");
            return (Criteria) this;
        }

        public Criteria andLeaveOffGreaterThan(String value) {
            addCriterion("LEAVE_OFF >", value, "leaveOff");
            return (Criteria) this;
        }

        public Criteria andLeaveOffGreaterThanOrEqualTo(String value) {
            addCriterion("LEAVE_OFF >=", value, "leaveOff");
            return (Criteria) this;
        }

        public Criteria andLeaveOffLessThan(String value) {
            addCriterion("LEAVE_OFF <", value, "leaveOff");
            return (Criteria) this;
        }

        public Criteria andLeaveOffLessThanOrEqualTo(String value) {
            addCriterion("LEAVE_OFF <=", value, "leaveOff");
            return (Criteria) this;
        }

        public Criteria andLeaveOffLike(String value) {
            addCriterion("LEAVE_OFF like", value, "leaveOff");
            return (Criteria) this;
        }

        public Criteria andLeaveOffNotLike(String value) {
            addCriterion("LEAVE_OFF not like", value, "leaveOff");
            return (Criteria) this;
        }

        public Criteria andLeaveOffIn(List<String> values) {
            addCriterion("LEAVE_OFF in", values, "leaveOff");
            return (Criteria) this;
        }

        public Criteria andLeaveOffNotIn(List<String> values) {
            addCriterion("LEAVE_OFF not in", values, "leaveOff");
            return (Criteria) this;
        }

        public Criteria andLeaveOffBetween(String value1, String value2) {
            addCriterion("LEAVE_OFF between", value1, value2, "leaveOff");
            return (Criteria) this;
        }

        public Criteria andLeaveOffNotBetween(String value1, String value2) {
            addCriterion("LEAVE_OFF not between", value1, value2, "leaveOff");
            return (Criteria) this;
        }

        public Criteria andTitleIsNull() {
            addCriterion("TITLE is null");
            return (Criteria) this;
        }

        public Criteria andTitleIsNotNull() {
            addCriterion("TITLE is not null");
            return (Criteria) this;
        }

        public Criteria andTitleEqualTo(String value) {
            addCriterion("TITLE =", value, "title");
            return (Criteria) this;
        }

        public Criteria andTitleNotEqualTo(String value) {
            addCriterion("TITLE <>", value, "title");
            return (Criteria) this;
        }

        public Criteria andTitleGreaterThan(String value) {
            addCriterion("TITLE >", value, "title");
            return (Criteria) this;
        }

        public Criteria andTitleGreaterThanOrEqualTo(String value) {
            addCriterion("TITLE >=", value, "title");
            return (Criteria) this;
        }

        public Criteria andTitleLessThan(String value) {
            addCriterion("TITLE <", value, "title");
            return (Criteria) this;
        }

        public Criteria andTitleLessThanOrEqualTo(String value) {
            addCriterion("TITLE <=", value, "title");
            return (Criteria) this;
        }

        public Criteria andTitleLike(String value) {
            addCriterion("TITLE like", value, "title");
            return (Criteria) this;
        }

        public Criteria andTitleNotLike(String value) {
            addCriterion("TITLE not like", value, "title");
            return (Criteria) this;
        }

        public Criteria andTitleIn(List<String> values) {
            addCriterion("TITLE in", values, "title");
            return (Criteria) this;
        }

        public Criteria andTitleNotIn(List<String> values) {
            addCriterion("TITLE not in", values, "title");
            return (Criteria) this;
        }

        public Criteria andTitleBetween(String value1, String value2) {
            addCriterion("TITLE between", value1, value2, "title");
            return (Criteria) this;
        }

        public Criteria andTitleNotBetween(String value1, String value2) {
            addCriterion("TITLE not between", value1, value2, "title");
            return (Criteria) this;
        }

        public Criteria andImcomeproveMonthIsNull() {
            addCriterion("IMCOMEPROVE_MONTH is null");
            return (Criteria) this;
        }

        public Criteria andImcomeproveMonthIsNotNull() {
            addCriterion("IMCOMEPROVE_MONTH is not null");
            return (Criteria) this;
        }

        public Criteria andImcomeproveMonthEqualTo(Integer value) {
            addCriterion("IMCOMEPROVE_MONTH =", value, "imcomeproveMonth");
            return (Criteria) this;
        }

        public Criteria andImcomeproveMonthNotEqualTo(Integer value) {
            addCriterion("IMCOMEPROVE_MONTH <>", value, "imcomeproveMonth");
            return (Criteria) this;
        }

        public Criteria andImcomeproveMonthGreaterThan(Integer value) {
            addCriterion("IMCOMEPROVE_MONTH >", value, "imcomeproveMonth");
            return (Criteria) this;
        }

        public Criteria andImcomeproveMonthGreaterThanOrEqualTo(Integer value) {
            addCriterion("IMCOMEPROVE_MONTH >=", value, "imcomeproveMonth");
            return (Criteria) this;
        }

        public Criteria andImcomeproveMonthLessThan(Integer value) {
            addCriterion("IMCOMEPROVE_MONTH <", value, "imcomeproveMonth");
            return (Criteria) this;
        }

        public Criteria andImcomeproveMonthLessThanOrEqualTo(Integer value) {
            addCriterion("IMCOMEPROVE_MONTH <=", value, "imcomeproveMonth");
            return (Criteria) this;
        }

        public Criteria andImcomeproveMonthIn(List<Integer> values) {
            addCriterion("IMCOMEPROVE_MONTH in", values, "imcomeproveMonth");
            return (Criteria) this;
        }

        public Criteria andImcomeproveMonthNotIn(List<Integer> values) {
            addCriterion("IMCOMEPROVE_MONTH not in", values, "imcomeproveMonth");
            return (Criteria) this;
        }

        public Criteria andImcomeproveMonthBetween(Integer value1, Integer value2) {
            addCriterion("IMCOMEPROVE_MONTH between", value1, value2, "imcomeproveMonth");
            return (Criteria) this;
        }

        public Criteria andImcomeproveMonthNotBetween(Integer value1, Integer value2) {
            addCriterion("IMCOMEPROVE_MONTH not between", value1, value2, "imcomeproveMonth");
            return (Criteria) this;
        }

        public Criteria andCurrentGradeIsNull() {
            addCriterion("CURRENT_GRADE is null");
            return (Criteria) this;
        }

        public Criteria andCurrentGradeIsNotNull() {
            addCriterion("CURRENT_GRADE is not null");
            return (Criteria) this;
        }

        public Criteria andCurrentGradeEqualTo(String value) {
            addCriterion("CURRENT_GRADE =", value, "currentGrade");
            return (Criteria) this;
        }

        public Criteria andCurrentGradeNotEqualTo(String value) {
            addCriterion("CURRENT_GRADE <>", value, "currentGrade");
            return (Criteria) this;
        }

        public Criteria andCurrentGradeGreaterThan(String value) {
            addCriterion("CURRENT_GRADE >", value, "currentGrade");
            return (Criteria) this;
        }

        public Criteria andCurrentGradeGreaterThanOrEqualTo(String value) {
            addCriterion("CURRENT_GRADE >=", value, "currentGrade");
            return (Criteria) this;
        }

        public Criteria andCurrentGradeLessThan(String value) {
            addCriterion("CURRENT_GRADE <", value, "currentGrade");
            return (Criteria) this;
        }

        public Criteria andCurrentGradeLessThanOrEqualTo(String value) {
            addCriterion("CURRENT_GRADE <=", value, "currentGrade");
            return (Criteria) this;
        }

        public Criteria andCurrentGradeLike(String value) {
            addCriterion("CURRENT_GRADE like", value, "currentGrade");
            return (Criteria) this;
        }

        public Criteria andCurrentGradeNotLike(String value) {
            addCriterion("CURRENT_GRADE not like", value, "currentGrade");
            return (Criteria) this;
        }

        public Criteria andCurrentGradeIn(List<String> values) {
            addCriterion("CURRENT_GRADE in", values, "currentGrade");
            return (Criteria) this;
        }

        public Criteria andCurrentGradeNotIn(List<String> values) {
            addCriterion("CURRENT_GRADE not in", values, "currentGrade");
            return (Criteria) this;
        }

        public Criteria andCurrentGradeBetween(String value1, String value2) {
            addCriterion("CURRENT_GRADE between", value1, value2, "currentGrade");
            return (Criteria) this;
        }

        public Criteria andCurrentGradeNotBetween(String value1, String value2) {
            addCriterion("CURRENT_GRADE not between", value1, value2, "currentGrade");
            return (Criteria) this;
        }

        public Criteria andUpGradeIsNull() {
            addCriterion("UP_GRADE is null");
            return (Criteria) this;
        }

        public Criteria andUpGradeIsNotNull() {
            addCriterion("UP_GRADE is not null");
            return (Criteria) this;
        }

        public Criteria andUpGradeEqualTo(String value) {
            addCriterion("UP_GRADE =", value, "upGrade");
            return (Criteria) this;
        }

        public Criteria andUpGradeNotEqualTo(String value) {
            addCriterion("UP_GRADE <>", value, "upGrade");
            return (Criteria) this;
        }

        public Criteria andUpGradeGreaterThan(String value) {
            addCriterion("UP_GRADE >", value, "upGrade");
            return (Criteria) this;
        }

        public Criteria andUpGradeGreaterThanOrEqualTo(String value) {
            addCriterion("UP_GRADE >=", value, "upGrade");
            return (Criteria) this;
        }

        public Criteria andUpGradeLessThan(String value) {
            addCriterion("UP_GRADE <", value, "upGrade");
            return (Criteria) this;
        }

        public Criteria andUpGradeLessThanOrEqualTo(String value) {
            addCriterion("UP_GRADE <=", value, "upGrade");
            return (Criteria) this;
        }

        public Criteria andUpGradeLike(String value) {
            addCriterion("UP_GRADE like", value, "upGrade");
            return (Criteria) this;
        }

        public Criteria andUpGradeNotLike(String value) {
            addCriterion("UP_GRADE not like", value, "upGrade");
            return (Criteria) this;
        }

        public Criteria andUpGradeIn(List<String> values) {
            addCriterion("UP_GRADE in", values, "upGrade");
            return (Criteria) this;
        }

        public Criteria andUpGradeNotIn(List<String> values) {
            addCriterion("UP_GRADE not in", values, "upGrade");
            return (Criteria) this;
        }

        public Criteria andUpGradeBetween(String value1, String value2) {
            addCriterion("UP_GRADE between", value1, value2, "upGrade");
            return (Criteria) this;
        }

        public Criteria andUpGradeNotBetween(String value1, String value2) {
            addCriterion("UP_GRADE not between", value1, value2, "upGrade");
            return (Criteria) this;
        }

        public Criteria andNameIsNull() {
            addCriterion("NAME is null");
            return (Criteria) this;
        }

        public Criteria andNameIsNotNull() {
            addCriterion("NAME is not null");
            return (Criteria) this;
        }

        public Criteria andNameEqualTo(String value) {
            addCriterion("NAME =", value, "name");
            return (Criteria) this;
        }

        public Criteria andNameNotEqualTo(String value) {
            addCriterion("NAME <>", value, "name");
            return (Criteria) this;
        }

        public Criteria andNameGreaterThan(String value) {
            addCriterion("NAME >", value, "name");
            return (Criteria) this;
        }

        public Criteria andNameGreaterThanOrEqualTo(String value) {
            addCriterion("NAME >=", value, "name");
            return (Criteria) this;
        }

        public Criteria andNameLessThan(String value) {
            addCriterion("NAME <", value, "name");
            return (Criteria) this;
        }

        public Criteria andNameLessThanOrEqualTo(String value) {
            addCriterion("NAME <=", value, "name");
            return (Criteria) this;
        }

        public Criteria andNameLike(String value) {
            addCriterion("NAME like", value, "name");
            return (Criteria) this;
        }

        public Criteria andNameNotLike(String value) {
            addCriterion("NAME not like", value, "name");
            return (Criteria) this;
        }

        public Criteria andNameIn(List<String> values) {
            addCriterion("NAME in", values, "name");
            return (Criteria) this;
        }

        public Criteria andNameNotIn(List<String> values) {
            addCriterion("NAME not in", values, "name");
            return (Criteria) this;
        }

        public Criteria andNameBetween(String value1, String value2) {
            addCriterion("NAME between", value1, value2, "name");
            return (Criteria) this;
        }

        public Criteria andNameNotBetween(String value1, String value2) {
            addCriterion("NAME not between", value1, value2, "name");
            return (Criteria) this;
        }

        public Criteria andAgentNameIsNull() {
            addCriterion("AGENT_NAME is null");
            return (Criteria) this;
        }

        public Criteria andAgentNameIsNotNull() {
            addCriterion("AGENT_NAME is not null");
            return (Criteria) this;
        }

        public Criteria andAgentNameEqualTo(String value) {
            addCriterion("AGENT_NAME =", value, "agentName");
            return (Criteria) this;
        }

        public Criteria andAgentNameNotEqualTo(String value) {
            addCriterion("AGENT_NAME <>", value, "agentName");
            return (Criteria) this;
        }

        public Criteria andAgentNameGreaterThan(String value) {
            addCriterion("AGENT_NAME >", value, "agentName");
            return (Criteria) this;
        }

        public Criteria andAgentNameGreaterThanOrEqualTo(String value) {
            addCriterion("AGENT_NAME >=", value, "agentName");
            return (Criteria) this;
        }

        public Criteria andAgentNameLessThan(String value) {
            addCriterion("AGENT_NAME <", value, "agentName");
            return (Criteria) this;
        }

        public Criteria andAgentNameLessThanOrEqualTo(String value) {
            addCriterion("AGENT_NAME <=", value, "agentName");
            return (Criteria) this;
        }

        public Criteria andAgentNameLike(String value) {
            addCriterion("AGENT_NAME like", value, "agentName");
            return (Criteria) this;
        }

        public Criteria andAgentNameNotLike(String value) {
            addCriterion("AGENT_NAME not like", value, "agentName");
            return (Criteria) this;
        }

        public Criteria andAgentNameIn(List<String> values) {
            addCriterion("AGENT_NAME in", values, "agentName");
            return (Criteria) this;
        }

        public Criteria andAgentNameNotIn(List<String> values) {
            addCriterion("AGENT_NAME not in", values, "agentName");
            return (Criteria) this;
        }

        public Criteria andAgentNameBetween(String value1, String value2) {
            addCriterion("AGENT_NAME between", value1, value2, "agentName");
            return (Criteria) this;
        }

        public Criteria andAgentNameNotBetween(String value1, String value2) {
            addCriterion("AGENT_NAME not between", value1, value2, "agentName");
            return (Criteria) this;
        }

        public Criteria andDescriptionLikeInsensitive(String value) {
            addCriterion("upper(DESCRIPTION) like", value.toUpperCase(), "description");
            return (Criteria) this;
        }

        public Criteria andTypeLikeInsensitive(String value) {
            addCriterion("upper(TYPE) like", value.toUpperCase(), "type");
            return (Criteria) this;
        }

        public Criteria andAgentCodeLikeInsensitive(String value) {
            addCriterion("upper(AGENT_CODE) like", value.toUpperCase(), "agentCode");
            return (Criteria) this;
        }

        public Criteria andLeaveOffLikeInsensitive(String value) {
            addCriterion("upper(LEAVE_OFF) like", value.toUpperCase(), "leaveOff");
            return (Criteria) this;
        }

        public Criteria andTitleLikeInsensitive(String value) {
            addCriterion("upper(TITLE) like", value.toUpperCase(), "title");
            return (Criteria) this;
        }

        public Criteria andCurrentGradeLikeInsensitive(String value) {
            addCriterion("upper(CURRENT_GRADE) like", value.toUpperCase(), "currentGrade");
            return (Criteria) this;
        }

        public Criteria andUpGradeLikeInsensitive(String value) {
            addCriterion("upper(UP_GRADE) like", value.toUpperCase(), "upGrade");
            return (Criteria) this;
        }

        public Criteria andNameLikeInsensitive(String value) {
            addCriterion("upper(NAME) like", value.toUpperCase(), "name");
            return (Criteria) this;
        }

        public Criteria andAgentNameLikeInsensitive(String value) {
            addCriterion("upper(AGENT_NAME) like", value.toUpperCase(), "agentName");
            return (Criteria) this;
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table fwd_oa_apply_form
     *
     * @mbggenerated do_not_delete_during_merge Mon Jun 04 14:47:17 CST 2018
     */
    public static class Criteria extends GeneratedCriteria {

        protected Criteria() {
            super();
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table fwd_oa_apply_form
     *
     * @mbggenerated Mon Jun 04 14:47:17 CST 2018
     */
    public static class Criterion {
        private String condition;

        private Object value;

        private Object secondValue;

        private boolean noValue;

        private boolean singleValue;

        private boolean betweenValue;

        private boolean listValue;

        private String typeHandler;

        public String getCondition() {
            return condition;
        }

        public Object getValue() {
            return value;
        }

        public Object getSecondValue() {
            return secondValue;
        }

        public boolean isNoValue() {
            return noValue;
        }

        public boolean isSingleValue() {
            return singleValue;
        }

        public boolean isBetweenValue() {
            return betweenValue;
        }

        public boolean isListValue() {
            return listValue;
        }

        public String getTypeHandler() {
            return typeHandler;
        }

        protected Criterion(String condition) {
            super();
            this.condition = condition;
            this.typeHandler = null;
            this.noValue = true;
        }

        protected Criterion(String condition, Object value, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.typeHandler = typeHandler;
            if (value instanceof List<?>) {
                this.listValue = true;
            } else {
                this.singleValue = true;
            }
        }

        protected Criterion(String condition, Object value) {
            this(condition, value, null);
        }

        protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.secondValue = secondValue;
            this.typeHandler = typeHandler;
            this.betweenValue = true;
        }

        protected Criterion(String condition, Object value, Object secondValue) {
            this(condition, value, secondValue, null);
        }
    }
}