package com.fulan.application.oa.domain;

import java.io.Serializable;
import java.util.Date;

import javax.validation.constraints.NotNull;

import com.fasterxml.jackson.annotation.JsonFormat;
import org.springframework.web.multipart.MultipartFile;

public class FwdOaApplyForm implements Serializable {
	private  MultipartFile file;
	
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column fwd_oa_apply_form.ID
     *
     * @mbggenerated Thu May 24 09:50:15 CST 2018
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column fwd_oa_apply_form.DESCRIPTION
     *
     * @mbggenerated Thu May 24 09:50:15 CST 2018
     */
    private String description;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column fwd_oa_apply_form.TYPE
     *
     * @mbggenerated Thu May 24 09:50:15 CST 2018
     */
    private String type;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column fwd_oa_apply_form.AGENT_CODE
     *
     * @mbggenerated Thu May 24 09:50:15 CST 2018
     */
    @NotNull
    private String agentCode;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column fwd_oa_apply_form.CREATE_DATETIME
     *
     * @mbggenerated Thu May 24 09:50:15 CST 2018
     */
    private Date createDatetime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column fwd_oa_apply_form.STATUS
     *
     * @mbggenerated Thu May 24 09:50:15 CST 2018
     */
    private Integer status; //0 表示正在审批当中了；1表示结束；2驳回。

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column fwd_oa_apply_form.START_TIME
     *
     * @mbggenerated Thu May 24 09:50:15 CST 2018
     */
//    @JsonFormat(pattern="yyyy-MM-dd HH:mm:ss",timezone = "GMT+8")
    private Date startTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column fwd_oa_apply_form.END_TIME
     *
     * @mbggenerated Thu May 24 09:50:15 CST 2018
     */
//    @JsonFormat(pattern="yyyy-MM-dd HH:mm:ss",timezone = "GMT+8")
    private Date endTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column fwd_oa_apply_form.END_DATETIME
     *
     * @mbggenerated Thu May 24 09:50:15 CST 2018
     */
    private Date endDatetime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column fwd_oa_apply_form.LEAVE_TYPE
     *
     * @mbggenerated Thu May 24 09:50:15 CST 2018
     */
    private Integer leaveType;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column fwd_oa_apply_form.LEAVE_OFF
     *
     * @mbggenerated Thu May 24 09:50:15 CST 2018
     */
    private String leaveOff;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column fwd_oa_apply_form.TITLE
     *
     * @mbggenerated Thu May 24 09:50:15 CST 2018
     */
    private String title;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column fwd_oa_apply_form.IMCOMEPROVE_MONTH
     *
     * @mbggenerated Thu May 24 09:50:15 CST 2018
     */
    private Integer imcomeproveMonth;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column fwd_oa_apply_form.CURRENT_GRADE
     *
     * @mbggenerated Thu May 24 09:50:15 CST 2018
     */
    private String currentGrade;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column fwd_oa_apply_form.UP_GRADE
     *
     * @mbggenerated Thu May 24 09:50:15 CST 2018
     */
    private String upGrade;

    private String name;

    private String agentName;

    private String[] files;
    
    public String getName() {
		return name;
	}

	public void setName(String name) {
		this.name = name;
	}

	public String getAgentName() {
		return agentName;
	}

	public void setAgentName(String agentName) {
		this.agentName = agentName;
	}

	/**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table fwd_oa_apply_form
     *
     * @mbggenerated Thu May 24 09:50:15 CST 2018
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column fwd_oa_apply_form.ID
     *
     * @return the value of fwd_oa_apply_form.ID
     *
     * @mbggenerated Thu May 24 09:50:15 CST 2018
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column fwd_oa_apply_form.ID
     *
     * @param id the value for fwd_oa_apply_form.ID
     *
     * @mbggenerated Thu May 24 09:50:15 CST 2018
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column fwd_oa_apply_form.DESCRIPTION
     *
     * @return the value of fwd_oa_apply_form.DESCRIPTION
     *
     * @mbggenerated Thu May 24 09:50:15 CST 2018
     */
    public String getDescription() {
        return description;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column fwd_oa_apply_form.DESCRIPTION
     *
     * @param description the value for fwd_oa_apply_form.DESCRIPTION
     *
     * @mbggenerated Thu May 24 09:50:15 CST 2018
     */
    public void setDescription(String description) {
        this.description = description == null ? null : description.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column fwd_oa_apply_form.TYPE
     *
     * @return the value of fwd_oa_apply_form.TYPE
     *
     * @mbggenerated Thu May 24 09:50:15 CST 2018
     */
    public String getType() {
        return type;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column fwd_oa_apply_form.TYPE
     *
     * @param type the value for fwd_oa_apply_form.TYPE
     *
     * @mbggenerated Thu May 24 09:50:15 CST 2018
     */
    public void setType(String type) {
        this.type = type == null ? null : type.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column fwd_oa_apply_form.AGENT_CODE
     *
     * @return the value of fwd_oa_apply_form.AGENT_CODE
     *
     * @mbggenerated Thu May 24 09:50:15 CST 2018
     */
    public String getAgentCode() {
        return agentCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column fwd_oa_apply_form.AGENT_CODE
     *
     * @param agentCode the value for fwd_oa_apply_form.AGENT_CODE
     *
     * @mbggenerated Thu May 24 09:50:15 CST 2018
     */
    public void setAgentCode(String agentCode) {
        this.agentCode = agentCode == null ? null : agentCode.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column fwd_oa_apply_form.CREATE_DATETIME
     *
     * @return the value of fwd_oa_apply_form.CREATE_DATETIME
     *
     * @mbggenerated Thu May 24 09:50:15 CST 2018
     */
    public Date getCreateDatetime() {
        return createDatetime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column fwd_oa_apply_form.CREATE_DATETIME
     *
     * @param createDatetime the value for fwd_oa_apply_form.CREATE_DATETIME
     *
     * @mbggenerated Thu May 24 09:50:15 CST 2018
     */
    public void setCreateDatetime(Date createDatetime) {
        this.createDatetime = createDatetime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column fwd_oa_apply_form.STATUS
     *
     * @return the value of fwd_oa_apply_form.STATUS
     *
     * @mbggenerated Thu May 24 09:50:15 CST 2018
     */
    public Integer getStatus() {
        return status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column fwd_oa_apply_form.STATUS
     *
     * @param status the value for fwd_oa_apply_form.STATUS
     *
     * @mbggenerated Thu May 24 09:50:15 CST 2018
     */
    public void setStatus(Integer status) {
        this.status = status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column fwd_oa_apply_form.START_TIME
     *
     * @return the value of fwd_oa_apply_form.START_TIME
     *
     * @mbggenerated Thu May 24 09:50:15 CST 2018
     */
    public Date getStartTime() {
        return startTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column fwd_oa_apply_form.START_TIME
     *
     * @param startTime the value for fwd_oa_apply_form.START_TIME
     *
     * @mbggenerated Thu May 24 09:50:15 CST 2018
     */
    public void setStartTime(Date startTime) {
        this.startTime = startTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column fwd_oa_apply_form.END_TIME
     *
     * @return the value of fwd_oa_apply_form.END_TIME
     *
     * @mbggenerated Thu May 24 09:50:15 CST 2018
     */
    public Date getEndTime() {
        return endTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column fwd_oa_apply_form.END_TIME
     *
     * @param endTime the value for fwd_oa_apply_form.END_TIME
     *
     * @mbggenerated Thu May 24 09:50:15 CST 2018
     */
    public void setEndTime(Date endTime) {
        this.endTime = endTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column fwd_oa_apply_form.END_DATETIME
     *
     * @return the value of fwd_oa_apply_form.END_DATETIME
     *
     * @mbggenerated Thu May 24 09:50:15 CST 2018
     */
    public Date getEndDatetime() {
        return endDatetime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column fwd_oa_apply_form.END_DATETIME
     *
     * @param endDatetime the value for fwd_oa_apply_form.END_DATETIME
     *
     * @mbggenerated Thu May 24 09:50:15 CST 2018
     */
    public void setEndDatetime(Date endDatetime) {
        this.endDatetime = endDatetime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column fwd_oa_apply_form.LEAVE_TYPE
     *
     * @return the value of fwd_oa_apply_form.LEAVE_TYPE
     *
     * @mbggenerated Thu May 24 09:50:15 CST 2018
     */
    public Integer getLeaveType() {
        return leaveType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column fwd_oa_apply_form.LEAVE_TYPE
     *
     * @param leaveType the value for fwd_oa_apply_form.LEAVE_TYPE
     *
     * @mbggenerated Thu May 24 09:50:15 CST 2018
     */
    public void setLeaveType(Integer leaveType) {
        this.leaveType = leaveType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column fwd_oa_apply_form.LEAVE_OFF
     *
     * @return the value of fwd_oa_apply_form.LEAVE_OFF
     *
     * @mbggenerated Thu May 24 09:50:15 CST 2018
     */
    public String getLeaveOff() {
        return leaveOff;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column fwd_oa_apply_form.LEAVE_OFF
     *
     * @param leaveOff the value for fwd_oa_apply_form.LEAVE_OFF
     *
     * @mbggenerated Thu May 24 09:50:15 CST 2018
     */
    public void setLeaveOff(String leaveOff) {
        this.leaveOff = leaveOff == null ? null : leaveOff.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column fwd_oa_apply_form.TITLE
     *
     * @return the value of fwd_oa_apply_form.TITLE
     *
     * @mbggenerated Thu May 24 09:50:15 CST 2018
     */
    public String getTitle() {
        return title;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column fwd_oa_apply_form.TITLE
     *
     * @param title the value for fwd_oa_apply_form.TITLE
     *
     * @mbggenerated Thu May 24 09:50:15 CST 2018
     */
    public void setTitle(String title) {
        this.title = title == null ? null : title.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column fwd_oa_apply_form.IMCOMEPROVE_MONTH
     *
     * @return the value of fwd_oa_apply_form.IMCOMEPROVE_MONTH
     *
     * @mbggenerated Thu May 24 09:50:15 CST 2018
     */
    public Integer getImcomeproveMonth() {
        return imcomeproveMonth;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column fwd_oa_apply_form.IMCOMEPROVE_MONTH
     *
     * @param imcomeproveMonth the value for fwd_oa_apply_form.IMCOMEPROVE_MONTH
     *
     * @mbggenerated Thu May 24 09:50:15 CST 2018
     */
    public void setImcomeproveMonth(Integer imcomeproveMonth) {
        this.imcomeproveMonth = imcomeproveMonth;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column fwd_oa_apply_form.CURRENT_GRADE
     *
     * @return the value of fwd_oa_apply_form.CURRENT_GRADE
     *
     * @mbggenerated Thu May 24 09:50:15 CST 2018
     */
    public String getCurrentGrade() {
        return currentGrade;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column fwd_oa_apply_form.CURRENT_GRADE
     *
     * @param currentGrade the value for fwd_oa_apply_form.CURRENT_GRADE
     *
     * @mbggenerated Thu May 24 09:50:15 CST 2018
     */
    public void setCurrentGrade(String currentGrade) {
        this.currentGrade = currentGrade == null ? null : currentGrade.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column fwd_oa_apply_form.UP_GRADE
     *
     * @return the value of fwd_oa_apply_form.UP_GRADE
     *
     * @mbggenerated Thu May 24 09:50:15 CST 2018
     */
    public String getUpGrade() {
        return upGrade;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column fwd_oa_apply_form.UP_GRADE
     *
     * @param upGrade the value for fwd_oa_apply_form.UP_GRADE
     *
     * @mbggenerated Thu May 24 09:50:15 CST 2018
     */
    public void setUpGrade(String upGrade) {
        this.upGrade = upGrade == null ? null : upGrade.trim();
    }

	public MultipartFile getFile() {
		return file;
	}

	public void setFile(MultipartFile file) {
		this.file = file;
	}

    public void setFiles(String[] files) {
        this.files = files;
    }

    public String[] getFiles() {
        return files;
    }
}