package com.zwo.modules.system.mapper;

import com.zwo.modules.system.domain.UserRole;
import com.zwo.modules.system.domain.UserRoleCriteria;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface UserRoleMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bhm_user_role
     *
     * @mbg.generated Thu Sep 20 15:54:32 CST 2018
     */
    long countByExample(UserRoleCriteria example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bhm_user_role
     *
     * @mbg.generated Thu Sep 20 15:54:32 CST 2018
     */
    int deleteByExample(UserRoleCriteria example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bhm_user_role
     *
     * @mbg.generated Thu Sep 20 15:54:32 CST 2018
     */
    int insert(UserRole record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bhm_user_role
     *
     * @mbg.generated Thu Sep 20 15:54:32 CST 2018
     */
    int insertSelective(UserRole record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bhm_user_role
     *
     * @mbg.generated Thu Sep 20 15:54:32 CST 2018
     */
    List<UserRole> selectByExample(UserRoleCriteria example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bhm_user_role
     *
     * @mbg.generated Thu Sep 20 15:54:32 CST 2018
     */
    int updateByExampleSelective(@Param("record") UserRole record, @Param("example") UserRoleCriteria example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bhm_user_role
     *
     * @mbg.generated Thu Sep 20 15:54:32 CST 2018
     */
    int updateByExample(@Param("record") UserRole record, @Param("example") UserRoleCriteria example);
}