package com.zwo.modules.mall.domain;

import java.io.Serializable;
import org.springframework.format.annotation.DateTimeFormat;

public class PrProductPropertyValue implements Serializable {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pr_product_property_value.ID
     *
     * @mbggenerated Sat Aug 05 10:56:51 CST 2017
     */
    private String id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pr_product_property_value.NAME
     *
     * @mbggenerated Sat Aug 05 10:56:51 CST 2017
     */
    private String name;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pr_product_property_value.CODE
     *
     * @mbggenerated Sat Aug 05 10:56:51 CST 2017
     */
    private String code;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pr_product_property_value.DESCRIPTION
     *
     * @mbggenerated Sat Aug 05 10:56:51 CST 2017
     */
    private String description;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pr_product_property_value.PROPERTY_ID
     *
     * @mbggenerated Sat Aug 05 10:56:51 CST 2017
     */
    private String propertyId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pr_product_property_value.IMAGE_ID
     *
     * @mbggenerated Sat Aug 05 10:56:51 CST 2017
     */
    private String imageId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pr_product_property_value.DISABLE
     *
     * @mbggenerated Sat Aug 05 10:56:51 CST 2017
     */
    private Boolean disable;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table pr_product_property_value
     *
     * @mbggenerated Sat Aug 05 10:56:51 CST 2017
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column pr_product_property_value.ID
     *
     * @return the value of pr_product_property_value.ID
     *
     * @mbggenerated Sat Aug 05 10:56:51 CST 2017
     */
    public String getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column pr_product_property_value.ID
     *
     * @param id the value for pr_product_property_value.ID
     *
     * @mbggenerated Sat Aug 05 10:56:51 CST 2017
     */
    public void setId(String id) {
        this.id = id == null ? null : id.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column pr_product_property_value.NAME
     *
     * @return the value of pr_product_property_value.NAME
     *
     * @mbggenerated Sat Aug 05 10:56:51 CST 2017
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column pr_product_property_value.NAME
     *
     * @param name the value for pr_product_property_value.NAME
     *
     * @mbggenerated Sat Aug 05 10:56:51 CST 2017
     */
    public void setName(String name) {
        this.name = name == null ? null : name.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column pr_product_property_value.CODE
     *
     * @return the value of pr_product_property_value.CODE
     *
     * @mbggenerated Sat Aug 05 10:56:51 CST 2017
     */
    public String getCode() {
        return code;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column pr_product_property_value.CODE
     *
     * @param code the value for pr_product_property_value.CODE
     *
     * @mbggenerated Sat Aug 05 10:56:51 CST 2017
     */
    public void setCode(String code) {
        this.code = code == null ? null : code.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column pr_product_property_value.DESCRIPTION
     *
     * @return the value of pr_product_property_value.DESCRIPTION
     *
     * @mbggenerated Sat Aug 05 10:56:51 CST 2017
     */
    public String getDescription() {
        return description;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column pr_product_property_value.DESCRIPTION
     *
     * @param description the value for pr_product_property_value.DESCRIPTION
     *
     * @mbggenerated Sat Aug 05 10:56:51 CST 2017
     */
    public void setDescription(String description) {
        this.description = description == null ? null : description.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column pr_product_property_value.PROPERTY_ID
     *
     * @return the value of pr_product_property_value.PROPERTY_ID
     *
     * @mbggenerated Sat Aug 05 10:56:51 CST 2017
     */
    public String getPropertyId() {
        return propertyId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column pr_product_property_value.PROPERTY_ID
     *
     * @param propertyId the value for pr_product_property_value.PROPERTY_ID
     *
     * @mbggenerated Sat Aug 05 10:56:51 CST 2017
     */
    public void setPropertyId(String propertyId) {
        this.propertyId = propertyId == null ? null : propertyId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column pr_product_property_value.IMAGE_ID
     *
     * @return the value of pr_product_property_value.IMAGE_ID
     *
     * @mbggenerated Sat Aug 05 10:56:51 CST 2017
     */
    public String getImageId() {
        return imageId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column pr_product_property_value.IMAGE_ID
     *
     * @param imageId the value for pr_product_property_value.IMAGE_ID
     *
     * @mbggenerated Sat Aug 05 10:56:51 CST 2017
     */
    public void setImageId(String imageId) {
        this.imageId = imageId == null ? null : imageId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column pr_product_property_value.DISABLE
     *
     * @return the value of pr_product_property_value.DISABLE
     *
     * @mbggenerated Sat Aug 05 10:56:51 CST 2017
     */
    public Boolean getDisable() {
        return disable;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column pr_product_property_value.DISABLE
     *
     * @param disable the value for pr_product_property_value.DISABLE
     *
     * @mbggenerated Sat Aug 05 10:56:51 CST 2017
     */
    public void setDisable(Boolean disable) {
        this.disable = disable;
    }
}