package com.fulan.application.oa.mapper;

import com.fulan.application.oa.domain.FwdOaAddress;

import com.fulan.application.oa.domain.FwdOaAddressExample;
import java.util.List;

import org.apache.ibatis.annotations.Mapper;
import org.apache.ibatis.annotations.Param;

@Mapper
public interface FwdOaAddressMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table fwd_oa_address
     *
     * @mbggenerated Tue May 22 14:05:31 CST 2018
     */
    int countByExample(FwdOaAddressExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table fwd_oa_address
     *
     * @mbggenerated Tue May 22 14:05:31 CST 2018
     */
    int deleteByExample(FwdOaAddressExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table fwd_oa_address
     *
     * @mbggenerated Tue May 22 14:05:31 CST 2018
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table fwd_oa_address
     *
     * @mbggenerated Tue May 22 14:05:31 CST 2018
     */
    int insert(FwdOaAddress record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table fwd_oa_address
     *
     * @mbggenerated Tue May 22 14:05:31 CST 2018
     */
    int insertSelective(FwdOaAddress record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table fwd_oa_address
     *
     * @mbggenerated Tue May 22 14:05:31 CST 2018
     */
    List<FwdOaAddress> selectByExample(FwdOaAddressExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table fwd_oa_address
     *
     * @mbggenerated Tue May 22 14:05:31 CST 2018
     */
    FwdOaAddress selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table fwd_oa_address
     *
     * @mbggenerated Tue May 22 14:05:31 CST 2018
     */
    int updateByExampleSelective(@Param("record") FwdOaAddress record, @Param("example") FwdOaAddressExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table fwd_oa_address
     *
     * @mbggenerated Tue May 22 14:05:31 CST 2018
     */
    int updateByExample(@Param("record") FwdOaAddress record, @Param("example") FwdOaAddressExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table fwd_oa_address
     *
     * @mbggenerated Tue May 22 14:05:31 CST 2018
     */
    int updateByPrimaryKeySelective(FwdOaAddress record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table fwd_oa_address
     *
     * @mbggenerated Tue May 22 14:05:31 CST 2018
     */
    int updateByPrimaryKey(FwdOaAddress record);
}