package com.fulan.application.oa.mapper;

import com.fulan.application.oa.domain.FwdOaFormAttachment;
import com.fulan.application.oa.domain.FwdOaFormAttachmentExample;
import java.util.List;

import org.apache.ibatis.annotations.Mapper;
import org.apache.ibatis.annotations.Param;

@Mapper
public interface FwdOaFormAttachmentMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table fwd_oa_form_attachment
     *
     * @mbggenerated Tue May 22 14:05:31 CST 2018
     */
    int countByExample(FwdOaFormAttachmentExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table fwd_oa_form_attachment
     *
     * @mbggenerated Tue May 22 14:05:31 CST 2018
     */
    int deleteByExample(FwdOaFormAttachmentExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table fwd_oa_form_attachment
     *
     * @mbggenerated Tue May 22 14:05:31 CST 2018
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table fwd_oa_form_attachment
     *
     * @mbggenerated Tue May 22 14:05:31 CST 2018
     */
    int insert(FwdOaFormAttachment record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table fwd_oa_form_attachment
     *
     * @mbggenerated Tue May 22 14:05:31 CST 2018
     */
    int insertSelective(FwdOaFormAttachment record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table fwd_oa_form_attachment
     *
     * @mbggenerated Tue May 22 14:05:31 CST 2018
     */
    List<FwdOaFormAttachment> selectByExample(FwdOaFormAttachmentExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table fwd_oa_form_attachment
     *
     * @mbggenerated Tue May 22 14:05:31 CST 2018
     */
    FwdOaFormAttachment selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table fwd_oa_form_attachment
     *
     * @mbggenerated Tue May 22 14:05:31 CST 2018
     */
    int updateByExampleSelective(@Param("record") FwdOaFormAttachment record, @Param("example") FwdOaFormAttachmentExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table fwd_oa_form_attachment
     *
     * @mbggenerated Tue May 22 14:05:31 CST 2018
     */
    int updateByExample(@Param("record") FwdOaFormAttachment record, @Param("example") FwdOaFormAttachmentExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table fwd_oa_form_attachment
     *
     * @mbggenerated Tue May 22 14:05:31 CST 2018
     */
    int updateByPrimaryKeySelective(FwdOaFormAttachment record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table fwd_oa_form_attachment
     *
     * @mbggenerated Tue May 22 14:05:31 CST 2018
     */
    int updateByPrimaryKey(FwdOaFormAttachment record);
}