package com.fulan.application.oa.mapper;

import java.util.List;

import org.apache.ibatis.annotations.Mapper;
import org.apache.ibatis.annotations.Param;

import com.fulan.application.oa.domain.FwdOaApplyForm;
import com.fulan.application.oa.domain.FwdOaApplyFormExample;
import com.fulan.application.oa.domain.FwdOaFormAttachment;
import com.fulan.application.oa.vo.OAApplyFormVo;
import com.fulan.application.oa.vo.OAApplyFormVoParameter;

@Mapper
public interface FwdOaApplyFormMapper{
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table fwd_oa_apply_form
     *
     * @mbggenerated Tue May 22 14:05:31 CST 2018
     */
    int countByExample(FwdOaApplyFormExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table fwd_oa_apply_form
     *
     * @mbggenerated Tue May 22 14:05:31 CST 2018
     */
    int deleteByExample(FwdOaApplyFormExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table fwd_oa_apply_form
     *
     * @mbggenerated Tue May 22 14:05:31 CST 2018
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table fwd_oa_apply_form
     *
     * @mbggenerated Tue May 22 14:05:31 CST 2018
     */
//    int insert(FwdOaApplyForm record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table fwd_oa_apply_form
     *
     * @mbggenerated Tue May 22 14:05:31 CST 2018
     */
    int insertSelective(FwdOaApplyForm record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table fwd_oa_apply_form
     *
     * @mbggenerated Tue May 22 14:05:31 CST 2018
     */
    List<FwdOaApplyForm> selectByExample(FwdOaApplyFormExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table fwd_oa_apply_form
     *
     * @mbggenerated Tue May 22 14:05:31 CST 2018
     */
    FwdOaApplyForm selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table fwd_oa_apply_form
     *
     * @mbggenerated Tue May 22 14:05:31 CST 2018
     */
    int updateByExampleSelective(@Param("record") FwdOaApplyForm record, @Param("example") FwdOaApplyFormExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table fwd_oa_apply_form
     *
     * @mbggenerated Tue May 22 14:05:31 CST 2018
     */
    int updateByExample(@Param("record") FwdOaApplyForm record, @Param("example") FwdOaApplyFormExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table fwd_oa_apply_form
     *
     * @mbggenerated Tue May 22 14:05:31 CST 2018
     */
    int updateByPrimaryKeySelective(FwdOaApplyForm record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table fwd_oa_apply_form
     *
     * @mbggenerated Tue May 22 14:05:31 CST 2018
     */
    int updateByPrimaryKey(FwdOaApplyForm record);
    
    /**
     * 传入参数FwdOaApplyForm的实例对象，
     * 判断其里面的type,status等属性，分页查询申请表单（主表），地址（子表），银行卡（子表），手机号（子表）
     * @param record
     * @param start
     * @param size
     * @return
     */
    List<OAApplyFormVo> selectOAApplyFormVo(@Param("parameter")OAApplyFormVoParameter parameter);
    
    List<FwdOaFormAttachment> selectAttamentsByFormId(@Param("formId") Integer formId);
}