package com.fulan.application.oa.mapper;

import com.fulan.application.oa.domain.FwdOaMobile;
import com.fulan.application.oa.domain.FwdOaMobileExample;
import java.util.List;

import org.apache.ibatis.annotations.Mapper;
import org.apache.ibatis.annotations.Param;

@Mapper
public interface FwdOaMobileMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table fwd_oa_mobile
     *
     * @mbggenerated Tue May 22 14:05:31 CST 2018
     */
    int countByExample(FwdOaMobileExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table fwd_oa_mobile
     *
     * @mbggenerated Tue May 22 14:05:31 CST 2018
     */
    int deleteByExample(FwdOaMobileExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table fwd_oa_mobile
     *
     * @mbggenerated Tue May 22 14:05:31 CST 2018
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table fwd_oa_mobile
     *
     * @mbggenerated Tue May 22 14:05:31 CST 2018
     */
    int insert(FwdOaMobile record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table fwd_oa_mobile
     *
     * @mbggenerated Tue May 22 14:05:31 CST 2018
     */
    int insertSelective(FwdOaMobile record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table fwd_oa_mobile
     *
     * @mbggenerated Tue May 22 14:05:31 CST 2018
     */
    List<FwdOaMobile> selectByExample(FwdOaMobileExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table fwd_oa_mobile
     *
     * @mbggenerated Tue May 22 14:05:31 CST 2018
     */
    FwdOaMobile selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table fwd_oa_mobile
     *
     * @mbggenerated Tue May 22 14:05:31 CST 2018
     */
    int updateByExampleSelective(@Param("record") FwdOaMobile record, @Param("example") FwdOaMobileExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table fwd_oa_mobile
     *
     * @mbggenerated Tue May 22 14:05:31 CST 2018
     */
    int updateByExample(@Param("record") FwdOaMobile record, @Param("example") FwdOaMobileExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table fwd_oa_mobile
     *
     * @mbggenerated Tue May 22 14:05:31 CST 2018
     */
    int updateByPrimaryKeySelective(FwdOaMobile record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table fwd_oa_mobile
     *
     * @mbggenerated Tue May 22 14:05:31 CST 2018
     */
    int updateByPrimaryKey(FwdOaMobile record);
}