package com.zwo.xiyangyang.modules.guess.dao;

import com.zwo.xiyangyang.modules.guess.domain.GuessQuestion;
import com.zwo.xiyangyang.modules.guess.domain.GuessQuestionCriteria;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface GuessQuestionMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table guess_question
     *
     * @mbggenerated Mon Mar 26 14:23:06 CST 2018
     */
    int countByExample(GuessQuestionCriteria example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table guess_question
     *
     * @mbggenerated Mon Mar 26 14:23:06 CST 2018
     */
    int deleteByExample(GuessQuestionCriteria example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table guess_question
     *
     * @mbggenerated Mon Mar 26 14:23:06 CST 2018
     */
    int deleteByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table guess_question
     *
     * @mbggenerated Mon Mar 26 14:23:06 CST 2018
     */
    int insert(GuessQuestion record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table guess_question
     *
     * @mbggenerated Mon Mar 26 14:23:06 CST 2018
     */
    int insertSelective(GuessQuestion record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table guess_question
     *
     * @mbggenerated Mon Mar 26 14:23:06 CST 2018
     */
    List<GuessQuestion> selectByExample(Object example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table guess_question
     *
     * @mbggenerated Mon Mar 26 14:23:06 CST 2018
     */
    GuessQuestion selectByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table guess_question
     *
     * @mbggenerated Mon Mar 26 14:23:06 CST 2018
     */
    int updateByExampleSelective(@Param("record") GuessQuestion record, @Param("example") GuessQuestionCriteria example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table guess_question
     *
     * @mbggenerated Mon Mar 26 14:23:06 CST 2018
     */
    int updateByExample(@Param("record") GuessQuestion record, @Param("example") GuessQuestionCriteria example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table guess_question
     *
     * @mbggenerated Mon Mar 26 14:23:06 CST 2018
     */
    int updateByPrimaryKeySelective(GuessQuestion record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table guess_question
     *
     * @mbggenerated Mon Mar 26 14:23:06 CST 2018
     */
    int updateByPrimaryKey(GuessQuestion record);
    
    /**
     * 更新猜中会员账号。
     * @param questionId
     * @param optionId
     */
    void updateMememberAcc(@Param("questionId")String questionId,@Param("optionId")String optionId);
    
    /**
     * 更新猜中会员账号历史记录。
     * @param questionId
     * @param optionId
     */
    void updateMememberHisAcc(@Param("questionId")String questionId,@Param("optionId")String optionId);
    
    
}