package com.zwo.modules.payment.dao;

import com.zwo.modules.payment.domain.PayTradePaymentOrder;
import com.zwo.modules.payment.domain.PayTradePaymentOrderCriteria;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface PayTradePaymentOrderMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pay_trade_payment_order
     *
     * @mbggenerated Wed Aug 02 07:04:04 CST 2017
     */
    int countByExample(PayTradePaymentOrderCriteria example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pay_trade_payment_order
     *
     * @mbggenerated Wed Aug 02 07:04:04 CST 2017
     */
    int deleteByExample(PayTradePaymentOrderCriteria example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pay_trade_payment_order
     *
     * @mbggenerated Wed Aug 02 07:04:04 CST 2017
     */
    int deleteByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pay_trade_payment_order
     *
     * @mbggenerated Wed Aug 02 07:04:04 CST 2017
     */
    int insert(PayTradePaymentOrder record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pay_trade_payment_order
     *
     * @mbggenerated Wed Aug 02 07:04:04 CST 2017
     */
    int insertSelective(PayTradePaymentOrder record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pay_trade_payment_order
     *
     * @mbggenerated Wed Aug 02 07:04:04 CST 2017
     */
    List<PayTradePaymentOrder> selectByExample(PayTradePaymentOrderCriteria example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pay_trade_payment_order
     *
     * @mbggenerated Wed Aug 02 07:04:04 CST 2017
     */
    PayTradePaymentOrder selectByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pay_trade_payment_order
     *
     * @mbggenerated Wed Aug 02 07:04:04 CST 2017
     */
    int updateByExampleSelective(@Param("record") PayTradePaymentOrder record, @Param("example") PayTradePaymentOrderCriteria example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pay_trade_payment_order
     *
     * @mbggenerated Wed Aug 02 07:04:04 CST 2017
     */
    int updateByExample(@Param("record") PayTradePaymentOrder record, @Param("example") PayTradePaymentOrderCriteria example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pay_trade_payment_order
     *
     * @mbggenerated Wed Aug 02 07:04:04 CST 2017
     */
    int updateByPrimaryKeySelective(PayTradePaymentOrder record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pay_trade_payment_order
     *
     * @mbggenerated Wed Aug 02 07:04:04 CST 2017
     */
    int updateByPrimaryKey(PayTradePaymentOrder record);
}