server:
  port: 8760
spring:
  application:
    name: gateway-service-zuul
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
  instance:
    prefer-ip-address: true
    ip-address: true
    instance-id: ${spring.application.name}:${spring.cloud.client.ip-address}:${spring.application.instance_id:${server.port}}
    hostname: ${spring.cloud.client.ip-address}
    lease-renewal-interval-in-seconds: 10
    lease-expiration-duration-in-seconds: 30   
zuul:
  routes:
    api-client:
      path: /client/**
      serviceId: service1
    api-client2:
      path: /client2/**
      serviceId: service2
      