package com.zwo.modules.mall.dao;

import com.zwo.modules.mall.domain.OrderTrade;
import com.zwo.modules.mall.domain.OrderTradeCriteria;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface OrderTradeMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table order_trade
     *
     * @mbggenerated Thu Aug 10 16:35:55 CST 2017
     */
    int countByExample(OrderTradeCriteria example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table order_trade
     *
     * @mbggenerated Thu Aug 10 16:35:55 CST 2017
     */
    int deleteByExample(OrderTradeCriteria example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table order_trade
     *
     * @mbggenerated Thu Aug 10 16:35:55 CST 2017
     */
    int deleteByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table order_trade
     *
     * @mbggenerated Thu Aug 10 16:35:55 CST 2017
     */
    int insert(OrderTrade record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table order_trade
     *
     * @mbggenerated Thu Aug 10 16:35:55 CST 2017
     */
    int insertSelective(OrderTrade record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table order_trade
     *
     * @mbggenerated Thu Aug 10 16:35:55 CST 2017
     */
    List<OrderTrade> selectByExample(OrderTradeCriteria example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table order_trade
     *
     * @mbggenerated Thu Aug 10 16:35:55 CST 2017
     */
    OrderTrade selectByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table order_trade
     *
     * @mbggenerated Thu Aug 10 16:35:55 CST 2017
     */
    int updateByExampleSelective(@Param("record") OrderTrade record, @Param("example") OrderTradeCriteria example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table order_trade
     *
     * @mbggenerated Thu Aug 10 16:35:55 CST 2017
     */
    int updateByExample(@Param("record") OrderTrade record, @Param("example") OrderTradeCriteria example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table order_trade
     *
     * @mbggenerated Thu Aug 10 16:35:55 CST 2017
     */
    int updateByPrimaryKeySelective(OrderTrade record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table order_trade
     *
     * @mbggenerated Thu Aug 10 16:35:55 CST 2017
     */
    int updateByPrimaryKey(OrderTrade record);
}